package erpsolscm.erpsolscmmodel.erpsolscmqvo;

import java.sql.CallableStatement;

import java.sql.SQLException;

import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 09 13:19:59 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwImeiTransactionHistoryQVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VwImeiTransactionHistoryQVOImpl() {
    }

    /**
     * Returns the bind variable value for P_ADF_IMEI_NO.
     * @return bind variable value for P_ADF_IMEI_NO
     */
    public String getP_ADF_IMEI_NO() {
        return (String) getNamedWhereClauseParam("P_ADF_IMEI_NO");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_IMEI_NO.
     * @param value value to bind as P_ADF_IMEI_NO
     */
    public void setP_ADF_IMEI_NO(String value) {
        setNamedWhereClauseParam("P_ADF_IMEI_NO", value);
    }
    @Override
    public void executeQuery() {
        // TODO Implement this method
        System.out.println("this is querying"+getNamedWhereClauseParam("P_ADF_IMEI_NO"));
        System.out.println("begin proc_set_gv_imei_no('" +
                                                       getNamedWhereClauseParam("P_ADF_IMEI_NO") + "'); end;"+ "plsql");
        CallableStatement cs =
            getDBTransaction().createCallableStatement("begin pkg_deploy_standard.proc_set_gv_imei_no('" +
                                                       getNamedWhereClauseParam("P_ADF_IMEI_NO") + "'); end;",
                                                       DBTransaction.DEFAULT);
        try {
            cs.executeUpdate();
        } catch (SQLException e) {
            try {
                e.printStackTrace();
                cs.close();
            } catch (SQLException f) {
                f.printStackTrace();
            }
        }
        finally{
            try {
                cs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        super.executeQuery();
    }
}

