package erpsolscm.erpsolscmmodel.erpsolscmqvo;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 07 15:27:26 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwSoSalesReportQVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Pk,
        Companyid,
        Regionid,
        Locationid,
        Storeid,
        Customerid,
        Salespersonid,
        Productgroup,
        Productid,
        txtCustomerName,
        txtSalespersonName,
        txtModelNo,
        txtStoreName,
        txtLocationName,
        txtFromDate,
        txtToDate,
        txtSalesTerritoryId,
        txtDoctypeId,
        txtDocumentID,
        Description,
        Divid,
        newSalespersonid,
        newSalespersonName,
        txtNewSalesTerritoryId,
        AccAllCompanyView,
        AccAllCustomersView,
        AccInItemsView,
        AccSoSalesPersonsView,
        AccAllStoresView,
        AccAllLocationsView,
        AccSoSalesTerritoryView,
        AccInStockItemGroupView,
        AccVWDocTypeForUnsubmitQVO,
        AccVWDocumentIdForUnsubmitQVO,
        AccAllDivisionsView,
        AccSoSalesPersonsNewView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PK = AttributesEnum.Pk.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int REGIONID = AttributesEnum.Regionid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int PRODUCTGROUP = AttributesEnum.Productgroup.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int TXTCUSTOMERNAME = AttributesEnum.txtCustomerName.index();
    public static final int TXTSALESPERSONNAME = AttributesEnum.txtSalespersonName.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTFROMDATE = AttributesEnum.txtFromDate.index();
    public static final int TXTTODATE = AttributesEnum.txtToDate.index();
    public static final int TXTSALESTERRITORYID = AttributesEnum.txtSalesTerritoryId.index();
    public static final int TXTDOCTYPEID = AttributesEnum.txtDoctypeId.index();
    public static final int TXTDOCUMENTID = AttributesEnum.txtDocumentID.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int DIVID = AttributesEnum.Divid.index();
    public static final int NEWSALESPERSONID = AttributesEnum.newSalespersonid.index();
    public static final int NEWSALESPERSONNAME = AttributesEnum.newSalespersonName.index();
    public static final int TXTNEWSALESTERRITORYID = AttributesEnum.txtNewSalesTerritoryId.index();
    public static final int ACCALLCOMPANYVIEW = AttributesEnum.AccAllCompanyView.index();
    public static final int ACCALLCUSTOMERSVIEW = AttributesEnum.AccAllCustomersView.index();
    public static final int ACCINITEMSVIEW = AttributesEnum.AccInItemsView.index();
    public static final int ACCSOSALESPERSONSVIEW = AttributesEnum.AccSoSalesPersonsView.index();
    public static final int ACCALLSTORESVIEW = AttributesEnum.AccAllStoresView.index();
    public static final int ACCALLLOCATIONSVIEW = AttributesEnum.AccAllLocationsView.index();
    public static final int ACCSOSALESTERRITORYVIEW = AttributesEnum.AccSoSalesTerritoryView.index();
    public static final int ACCINSTOCKITEMGROUPVIEW = AttributesEnum.AccInStockItemGroupView.index();
    public static final int ACCVWDOCTYPEFORUNSUBMITQVO = AttributesEnum.AccVWDocTypeForUnsubmitQVO.index();
    public static final int ACCVWDOCUMENTIDFORUNSUBMITQVO = AttributesEnum.AccVWDocumentIdForUnsubmitQVO.index();
    public static final int ACCALLDIVISIONSVIEW = AttributesEnum.AccAllDivisionsView.index();
    public static final int ACCSOSALESPERSONSNEWVIEW = AttributesEnum.AccSoSalesPersonsNewView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VwSoSalesReportQVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Pk.
     * @return the Pk
     */
    public Integer getPk() {
        return (Integer) getAttributeInternal(PK);
    }

    /**
     * Gets the attribute value for the calculated attribute Companyid.
     * @return the Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Companyid.
     * @param value value to set the  Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Regionid.
     * @return the Regionid
     */
    public String getRegionid() {
        return (String) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Regionid.
     * @param value value to set the  Regionid
     */
    public void setRegionid(String value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Locationid.
     * @return the Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Locationid.
     * @param value value to set the  Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Storeid.
     * @return the Storeid
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Storeid.
     * @param value value to set the  Storeid
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Customerid.
     * @return the Customerid
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Customerid.
     * @param value value to set the  Customerid
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Salespersonid.
     * @return the Salespersonid
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Salespersonid.
     * @param value value to set the  Salespersonid
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Productgroup.
     * @return the Productgroup
     */
    public String getProductgroup() {
        return (String) getAttributeInternal(PRODUCTGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Productgroup.
     * @param value value to set the  Productgroup
     */
    public void setProductgroup(String value) {
        setAttributeInternal(PRODUCTGROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Productid.
     * @return the Productid
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Productid.
     * @param value value to set the  Productid
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtCustomerName.
     * @return the txtCustomerName
     */
    public String gettxtCustomerName() {
        return (String) getAttributeInternal(TXTCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtCustomerName.
     * @param value value to set the  txtCustomerName
     */
    public void settxtCustomerName(String value) {
        setAttributeInternal(TXTCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSalespersonName.
     * @return the txtSalespersonName
     */
    public String gettxtSalespersonName() {
        return (String) getAttributeInternal(TXTSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSalespersonName.
     * @param value value to set the  txtSalespersonName
     */
    public void settxtSalespersonName(String value) {
        setAttributeInternal(TXTSALESPERSONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtModelNo.
     * @return the txtModelNo
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtModelNo.
     * @param value value to set the  txtModelNo
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtStoreName.
     * @return the txtStoreName
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtStoreName.
     * @param value value to set the  txtStoreName
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtLocationName.
     * @return the txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtLocationName.
     * @param value value to set the  txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtFromDate.
     * @return the txtFromDate
     */
    public Date gettxtFromDate() {
        return (Date) getAttributeInternal(TXTFROMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtFromDate.
     * @param value value to set the  txtFromDate
     */
    public void settxtFromDate(Date value) {
        setAttributeInternal(TXTFROMDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtToDate.
     * @return the txtToDate
     */
    public Date gettxtToDate() {
        return (Date) getAttributeInternal(TXTTODATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtToDate.
     * @param value value to set the  txtToDate
     */
    public void settxtToDate(Date value) {
        setAttributeInternal(TXTTODATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtSalesTerritoryId.
     * @return the txtSalesTerritoryId
     */
    public String gettxtSalesTerritoryId() {
        return (String) getAttributeInternal(TXTSALESTERRITORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSalesTerritoryId.
     * @param value value to set the  txtSalesTerritoryId
     */
    public void settxtSalesTerritoryId(String value) {
        setAttributeInternal(TXTSALESTERRITORYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtDoctypeId.
     * @return the txtDoctypeId
     */
    public String gettxtDoctypeId() {
        return (String) getAttributeInternal(TXTDOCTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtDoctypeId.
     * @param value value to set the  txtDoctypeId
     */
    public void settxtDoctypeId(String value) {
        setAttributeInternal(TXTDOCTYPEID, value);
        settxtDocumentID(null);
    }

    /**
     * Gets the attribute value for the calculated attribute txtDocumentID.
     * @return the txtDocumentID
     */
    public String gettxtDocumentID() {
        return (String) getAttributeInternal(TXTDOCUMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtDocumentID.
     * @param value value to set the  txtDocumentID
     */
    public void settxtDocumentID(String value) {
        setAttributeInternal(TXTDOCUMENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Divid.
     * @return the Divid
     */
    public String getDivid() {
        return (String) getAttributeInternal(DIVID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Divid.
     * @param value value to set the  Divid
     */
    public void setDivid(String value) {
        setAttributeInternal(DIVID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute newSalespersonid.
     * @return the newSalespersonid
     */
    public String getnewSalespersonid() {
        return (String) getAttributeInternal(NEWSALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute newSalespersonid.
     * @param value value to set the  newSalespersonid
     */
    public void setnewSalespersonid(String value) {
        setAttributeInternal(NEWSALESPERSONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute newSalespersonName.
     * @return the newSalespersonName
     */
    public String getnewSalespersonName() {
        return (String) getAttributeInternal(NEWSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute newSalespersonName.
     * @param value value to set the  newSalespersonName
     */
    public void setnewSalespersonName(String value) {
        setAttributeInternal(NEWSALESPERSONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtNewSalesTerritoryId.
     * @return the txtNewSalesTerritoryId
     */
    public String gettxtNewSalesTerritoryId() {
        return (String) getAttributeInternal(TXTNEWSALESTERRITORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtNewSalesTerritoryId.
     * @param value value to set the  txtNewSalesTerritoryId
     */
    public void settxtNewSalesTerritoryId(String value) {
        setAttributeInternal(TXTNEWSALESTERRITORYID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCompanyView.
     */
    public RowSet getAccAllCompanyView() {
        return (RowSet) getAttributeInternal(ACCALLCOMPANYVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomersView.
     */
    public RowSet getAccAllCustomersView() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInItemsView.
     */
    public RowSet getAccInItemsView() {
        return (RowSet) getAttributeInternal(ACCINITEMSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsView.
     */
    public RowSet getAccSoSalesPersonsView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresView.
     */
    public RowSet getAccAllStoresView() {
        return (RowSet) getAttributeInternal(ACCALLSTORESVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsView.
     */
    public RowSet getAccAllLocationsView() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesTerritoryView.
     */
    public RowSet getAccSoSalesTerritoryView() {
        return (RowSet) getAttributeInternal(ACCSOSALESTERRITORYVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInStockItemGroupView.
     */
    public RowSet getAccInStockItemGroupView() {
        return (RowSet) getAttributeInternal(ACCINSTOCKITEMGROUPVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWDocTypeForUnsubmitQVO.
     */
    public RowSet getAccVWDocTypeForUnsubmitQVO() {
        return (RowSet) getAttributeInternal(ACCVWDOCTYPEFORUNSUBMITQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWDocumentIdForUnsubmitQVO.
     */
    public RowSet getAccVWDocumentIdForUnsubmitQVO() {
        return (RowSet) getAttributeInternal(ACCVWDOCUMENTIDFORUNSUBMITQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllDivisionsView.
     */
    public RowSet getAccAllDivisionsView() {
        return (RowSet) getAttributeInternal(ACCALLDIVISIONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsNewView.
     */
    public RowSet getAccSoSalesPersonsNewView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSNEWVIEW);
    }
}

