package erpsolscm.erpsolscmmodel.erpsolscmqvo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;

import erpsolscm.erpsolscmmodel.erpsolscmqvo.common.VwSoSalesReportQVO;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 03 18:37:31 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VwSoSalesReportQVOImpl extends ViewObjectImpl implements VwSoSalesReportQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public VwSoSalesReportQVOImpl() {
    }
    
    public void doSetERPSolSCMReportDefault() {
        ViewObject vo=getApplicationModule().findViewObject("QvoSaleLoc");
        if (vo!=null) {
            vo.remove();
       }
        vo=getApplicationModule().createViewObjectFromQueryStmt("QvoSaleLoc", "select locationid, location_description from all_locations where locationid='"+ERPSolGlobClassModel.doGetUserLocationCode()+"'");
        vo.executeQuery();;
        this.first().setAttribute("Locationid", vo.first().getAttribute(0));
        this.first().setAttribute("txtLocationName", vo.first().getAttribute(1));
        this.first().setAttribute("Companyid", ERPSolGlobClassModel.doGetUserCompanyCode());
//        this.first().setAttribute("txtFromDate", this.first().getAttribute("txtDefaultDate"));
//        this.first().setAttribute("txtToDate", this.first().getAttribute("txtDefaultDate"));
        vo.remove();
    }
}

