package erpsolscm.erpsolscmmodel.erpsolscmqvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 26 09:39:43 PKT 2022
// ---------------------------------------------------------------------
public interface VwSaleReturnForRateChangeQVORow extends Row {
    void doUpdateSaleReturnProductRate();
}

