package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolscm.erpsolscmmodel.erpsolscmeo.SoSalesReturnImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 27 11:55:24 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoSalesReturnViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_SOSALESRETURN = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Salesretid,
        ReturnDate,
        Customerid,
        Locationid,
        Salespersonid,
        Salesterritoryid,
        Createdby,
        Posted,
        CreatedDate,
        Modifiedby,
        PostedBy,
        ModifiedDate,
        Companyid,
        Deptid,
        Invoiceid,
        GlvoucherNo,
        PostToIntFace,
        PostToGl,
        DocTypeId,
        ArPosted,
        StPercent,
        ReturnType,
        Pid,
        Remarks,
        RemarksNarr,
        SedPercent,
        ExtraTaxPercent,
        OldInvoiceid,
        Storeid,
        GrnRef,
        Catid,
        IsAuto,
        IsMigrated,
        MigratedDate,
        RebateId,
        LocCurrcode,
        ExchangeRate,
        ReferenceTransId,
        ReferenceTransType,
        Submit,
        SymptomDate,
        EbsCustomerId,
        EbsSalespersonId,
        EbsLocationId,
        EbsStoreId,
        Supplierid,
        ConsignmentNo,
        Salesretseq,
        txtCustomerName,
        txtSalesPersonName,
        txtSupplierName,
        txtStoreName,
        ManualRefNo,
        Divid,
        SoSalesReturnLinesView,
        SrimeiView,
        AllCustomersView,
        SoSalesPersonsView,
        PuSuppliersView,
        AllStoresView,
        AccSretCategoryView,
        AccAllCustomersView,
        AccSoSalesPersonsView,
        AccSoSalesPersonsDefView,
        AccAllCustomerSalespersonPid,
        AccPuSuppliersView,
        AccAllStoresView,
        AccVWYesNoQVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESRETID = AttributesEnum.Salesretid.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int SALESTERRITORYID = AttributesEnum.Salesterritoryid.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int POSTEDBY = AttributesEnum.PostedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int INVOICEID = AttributesEnum.Invoiceid.index();
    public static final int GLVOUCHERNO = AttributesEnum.GlvoucherNo.index();
    public static final int POSTTOINTFACE = AttributesEnum.PostToIntFace.index();
    public static final int POSTTOGL = AttributesEnum.PostToGl.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int ARPOSTED = AttributesEnum.ArPosted.index();
    public static final int STPERCENT = AttributesEnum.StPercent.index();
    public static final int RETURNTYPE = AttributesEnum.ReturnType.index();
    public static final int PID = AttributesEnum.Pid.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int REMARKSNARR = AttributesEnum.RemarksNarr.index();
    public static final int SEDPERCENT = AttributesEnum.SedPercent.index();
    public static final int EXTRATAXPERCENT = AttributesEnum.ExtraTaxPercent.index();
    public static final int OLDINVOICEID = AttributesEnum.OldInvoiceid.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int GRNREF = AttributesEnum.GrnRef.index();
    public static final int CATID = AttributesEnum.Catid.index();
    public static final int ISAUTO = AttributesEnum.IsAuto.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int REBATEID = AttributesEnum.RebateId.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int REFERENCETRANSID = AttributesEnum.ReferenceTransId.index();
    public static final int REFERENCETRANSTYPE = AttributesEnum.ReferenceTransType.index();
    public static final int SUBMIT = AttributesEnum.Submit.index();
    public static final int SYMPTOMDATE = AttributesEnum.SymptomDate.index();
    public static final int EBSCUSTOMERID = AttributesEnum.EbsCustomerId.index();
    public static final int EBSSALESPERSONID = AttributesEnum.EbsSalespersonId.index();
    public static final int EBSLOCATIONID = AttributesEnum.EbsLocationId.index();
    public static final int EBSSTOREID = AttributesEnum.EbsStoreId.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int CONSIGNMENTNO = AttributesEnum.ConsignmentNo.index();
    public static final int SALESRETSEQ = AttributesEnum.Salesretseq.index();
    public static final int TXTCUSTOMERNAME = AttributesEnum.txtCustomerName.index();
    public static final int TXTSALESPERSONNAME = AttributesEnum.txtSalesPersonName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int MANUALREFNO = AttributesEnum.ManualRefNo.index();
    public static final int DIVID = AttributesEnum.Divid.index();
    public static final int SOSALESRETURNLINESVIEW = AttributesEnum.SoSalesReturnLinesView.index();
    public static final int SRIMEIVIEW = AttributesEnum.SrimeiView.index();
    public static final int ALLCUSTOMERSVIEW = AttributesEnum.AllCustomersView.index();
    public static final int SOSALESPERSONSVIEW = AttributesEnum.SoSalesPersonsView.index();
    public static final int PUSUPPLIERSVIEW = AttributesEnum.PuSuppliersView.index();
    public static final int ALLSTORESVIEW = AttributesEnum.AllStoresView.index();
    public static final int ACCSRETCATEGORYVIEW = AttributesEnum.AccSretCategoryView.index();
    public static final int ACCALLCUSTOMERSVIEW = AttributesEnum.AccAllCustomersView.index();
    public static final int ACCSOSALESPERSONSVIEW = AttributesEnum.AccSoSalesPersonsView.index();
    public static final int ACCSOSALESPERSONSDEFVIEW = AttributesEnum.AccSoSalesPersonsDefView.index();
    public static final int ACCALLCUSTOMERSALESPERSONPID = AttributesEnum.AccAllCustomerSalespersonPid.index();
    public static final int ACCPUSUPPLIERSVIEW = AttributesEnum.AccPuSuppliersView.index();
    public static final int ACCALLSTORESVIEW = AttributesEnum.AccAllStoresView.index();
    public static final int ACCVWYESNOQVO = AttributesEnum.AccVWYesNoQVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoSalesReturnViewRowImpl() {
    }

    /**
     * Gets SoSalesReturn entity object.
     * @return the SoSalesReturn
     */
    public SoSalesReturnImpl getSoSalesReturn() {
        return (SoSalesReturnImpl) getEntity(ENTITY_SOSALESRETURN);
    }

    /**
     * Gets the attribute value for SALESRETID using the alias name Salesretid.
     * @return the SALESRETID
     */
    public String getSalesretid() {
        return (String) getAttributeInternal(SALESRETID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESRETID using the alias name Salesretid.
     * @param value value to set the SALESRETID
     */
    public void setSalesretid(String value) {
        setAttributeInternal(SALESRETID, value);
    }

    /**
     * Gets the attribute value for RETURN_DATE using the alias name ReturnDate.
     * @return the RETURN_DATE
     */
    public Date getReturnDate() {
        return (Date) getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURN_DATE using the alias name ReturnDate.
     * @param value value to set the RETURN_DATE
     */
    public void setReturnDate(Date value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for CUSTOMERID using the alias name Customerid.
     * @return the CUSTOMERID
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMERID using the alias name Customerid.
     * @param value value to set the CUSTOMERID
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
        try {
            getAccSoSalesPersonsDefView().setNamedWhereClauseParam("P_ADF_CUSTOMERID", (value==null?"-":value));
            getAccSoSalesPersonsDefView().executeQuery();
            setSalespersonid(getAccSoSalesPersonsDefView().first().getAttribute("Salespersonid").toString());
        } catch (Exception e) {
            setSalespersonid(null);
            // TODO: Add catch code
            e.printStackTrace();
        }        
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for SALESPERSONID using the alias name Salespersonid.
     * @return the SALESPERSONID
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESPERSONID using the alias name Salespersonid.
     * @param value value to set the SALESPERSONID
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
        getAccAllCustomerSalespersonPid().setNamedWhereClauseParam("P_ADF_CUSTOMERID", getCustomerid());
        getAccAllCustomerSalespersonPid().setNamedWhereClauseParam("P_ADF_SALESPERSONID", value);
        getAccAllCustomerSalespersonPid().executeQuery();
        setDivid(getAccAllCustomerSalespersonPid().first().getAttribute("Divid").toString());        
    }

    /**
     * Gets the attribute value for SALESTERRITORYID using the alias name Salesterritoryid.
     * @return the SALESTERRITORYID
     */
    public String getSalesterritoryid() {
        return (String) getAttributeInternal(SALESTERRITORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESTERRITORYID using the alias name Salesterritoryid.
     * @param value value to set the SALESTERRITORYID
     */
    public void setSalesterritoryid(String value) {
        setAttributeInternal(SALESTERRITORYID, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for POSTED_BY using the alias name PostedBy.
     * @return the POSTED_BY
     */
    public String getPostedBy() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED_BY using the alias name PostedBy.
     * @param value value to set the POSTED_BY
     */
    public void setPostedBy(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for DEPTID using the alias name Deptid.
     * @return the DEPTID
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPTID using the alias name Deptid.
     * @param value value to set the DEPTID
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for INVOICEID using the alias name Invoiceid.
     * @return the INVOICEID
     */
    public String getInvoiceid() {
        return (String) getAttributeInternal(INVOICEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICEID using the alias name Invoiceid.
     * @param value value to set the INVOICEID
     */
    public void setInvoiceid(String value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**
     * Gets the attribute value for GLVOUCHER_NO using the alias name GlvoucherNo.
     * @return the GLVOUCHER_NO
     */
    public String getGlvoucherNo() {
        return (String) getAttributeInternal(GLVOUCHERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GLVOUCHER_NO using the alias name GlvoucherNo.
     * @param value value to set the GLVOUCHER_NO
     */
    public void setGlvoucherNo(String value) {
        setAttributeInternal(GLVOUCHERNO, value);
    }

    /**
     * Gets the attribute value for POST_TO_INT_FACE using the alias name PostToIntFace.
     * @return the POST_TO_INT_FACE
     */
    public String getPostToIntFace() {
        return (String) getAttributeInternal(POSTTOINTFACE);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_INT_FACE using the alias name PostToIntFace.
     * @param value value to set the POST_TO_INT_FACE
     */
    public void setPostToIntFace(String value) {
        setAttributeInternal(POSTTOINTFACE, value);
    }

    /**
     * Gets the attribute value for POST_TO_GL using the alias name PostToGl.
     * @return the POST_TO_GL
     */
    public String getPostToGl() {
        return (String) getAttributeInternal(POSTTOGL);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_TO_GL using the alias name PostToGl.
     * @param value value to set the POST_TO_GL
     */
    public void setPostToGl(String value) {
        setAttributeInternal(POSTTOGL, value);
    }

    /**
     * Gets the attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @return the DOC_TYPE_ID
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TYPE_ID using the alias name DocTypeId.
     * @param value value to set the DOC_TYPE_ID
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for AR_POSTED using the alias name ArPosted.
     * @return the AR_POSTED
     */
    public String getArPosted() {
        return (String) getAttributeInternal(ARPOSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for AR_POSTED using the alias name ArPosted.
     * @param value value to set the AR_POSTED
     */
    public void setArPosted(String value) {
        setAttributeInternal(ARPOSTED, value);
    }

    /**
     * Gets the attribute value for ST_PERCENT using the alias name StPercent.
     * @return the ST_PERCENT
     */
    public BigDecimal getStPercent() {
        return (BigDecimal) getAttributeInternal(STPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for ST_PERCENT using the alias name StPercent.
     * @param value value to set the ST_PERCENT
     */
    public void setStPercent(BigDecimal value) {
        setAttributeInternal(STPERCENT, value);
    }

    /**
     * Gets the attribute value for RETURN_TYPE using the alias name ReturnType.
     * @return the RETURN_TYPE
     */
    public String getReturnType() {
        return (String) getAttributeInternal(RETURNTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURN_TYPE using the alias name ReturnType.
     * @param value value to set the RETURN_TYPE
     */
    public void setReturnType(String value) {
        setAttributeInternal(RETURNTYPE, value);
    }

    /**
     * Gets the attribute value for PID using the alias name Pid.
     * @return the PID
     */
    public Integer getPid() {
        return (Integer) getAttributeInternal(PID);
    }

    /**
     * Sets <code>value</code> as attribute value for PID using the alias name Pid.
     * @param value value to set the PID
     */
    public void setPid(Integer value) {
        setAttributeInternal(PID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for REMARKS_NARR using the alias name RemarksNarr.
     * @return the REMARKS_NARR
     */
    public String getRemarksNarr() {
        return (String) getAttributeInternal(REMARKSNARR);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS_NARR using the alias name RemarksNarr.
     * @param value value to set the REMARKS_NARR
     */
    public void setRemarksNarr(String value) {
        setAttributeInternal(REMARKSNARR, value);
    }

    /**
     * Gets the attribute value for SED_PERCENT using the alias name SedPercent.
     * @return the SED_PERCENT
     */
    public BigDecimal getSedPercent() {
        return (BigDecimal) getAttributeInternal(SEDPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SED_PERCENT using the alias name SedPercent.
     * @param value value to set the SED_PERCENT
     */
    public void setSedPercent(BigDecimal value) {
        setAttributeInternal(SEDPERCENT, value);
    }

    /**
     * Gets the attribute value for EXTRA_TAX_PERCENT using the alias name ExtraTaxPercent.
     * @return the EXTRA_TAX_PERCENT
     */
    public BigDecimal getExtraTaxPercent() {
        return (BigDecimal) getAttributeInternal(EXTRATAXPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTRA_TAX_PERCENT using the alias name ExtraTaxPercent.
     * @param value value to set the EXTRA_TAX_PERCENT
     */
    public void setExtraTaxPercent(BigDecimal value) {
        setAttributeInternal(EXTRATAXPERCENT, value);
    }

    /**
     * Gets the attribute value for OLD_INVOICEID using the alias name OldInvoiceid.
     * @return the OLD_INVOICEID
     */
    public String getOldInvoiceid() {
        return (String) getAttributeInternal(OLDINVOICEID);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_INVOICEID using the alias name OldInvoiceid.
     * @param value value to set the OLD_INVOICEID
     */
    public void setOldInvoiceid(String value) {
        setAttributeInternal(OLDINVOICEID, value);
    }

    /**
     * Gets the attribute value for STOREID using the alias name Storeid.
     * @return the STOREID
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STOREID using the alias name Storeid.
     * @param value value to set the STOREID
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for GRN_REF using the alias name GrnRef.
     * @return the GRN_REF
     */
    public String getGrnRef() {
        return (String) getAttributeInternal(GRNREF);
    }

    /**
     * Sets <code>value</code> as attribute value for GRN_REF using the alias name GrnRef.
     * @param value value to set the GRN_REF
     */
    public void setGrnRef(String value) {
        setAttributeInternal(GRNREF, value);
    }

    /**
     * Gets the attribute value for CATID using the alias name Catid.
     * @return the CATID
     */
    public String getCatid() {
        return (String) getAttributeInternal(CATID);
    }

    /**
     * Sets <code>value</code> as attribute value for CATID using the alias name Catid.
     * @param value value to set the CATID
     */
    public void setCatid(String value) {
        setAttributeInternal(CATID, value);
    }

    /**
     * Gets the attribute value for IS_AUTO using the alias name IsAuto.
     * @return the IS_AUTO
     */
    public String getIsAuto() {
        return (String) getAttributeInternal(ISAUTO);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_AUTO using the alias name IsAuto.
     * @param value value to set the IS_AUTO
     */
    public void setIsAuto(String value) {
        setAttributeInternal(ISAUTO, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for REBATE_ID using the alias name RebateId.
     * @return the REBATE_ID
     */
    public String getRebateId() {
        return (String) getAttributeInternal(REBATEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REBATE_ID using the alias name RebateId.
     * @param value value to set the REBATE_ID
     */
    public void setRebateId(String value) {
        setAttributeInternal(REBATEID, value);
    }

    /**
     * Gets the attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @return the LOC_CURRCODE
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOC_CURRCODE using the alias name LocCurrcode.
     * @param value value to set the LOC_CURRCODE
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public BigDecimal getExchangeRate() {
        return (BigDecimal) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(BigDecimal value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for REFERENCE_TRANS_ID using the alias name ReferenceTransId.
     * @return the REFERENCE_TRANS_ID
     */
    public String getReferenceTransId() {
        return (String) getAttributeInternal(REFERENCETRANSID);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_TRANS_ID using the alias name ReferenceTransId.
     * @param value value to set the REFERENCE_TRANS_ID
     */
    public void setReferenceTransId(String value) {
        setAttributeInternal(REFERENCETRANSID, value);
    }

    /**
     * Gets the attribute value for REFERENCE_TRANS_TYPE using the alias name ReferenceTransType.
     * @return the REFERENCE_TRANS_TYPE
     */
    public String getReferenceTransType() {
        return (String) getAttributeInternal(REFERENCETRANSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_TRANS_TYPE using the alias name ReferenceTransType.
     * @param value value to set the REFERENCE_TRANS_TYPE
     */
    public void setReferenceTransType(String value) {
        setAttributeInternal(REFERENCETRANSTYPE, value);
    }

    /**
     * Gets the attribute value for SUBMIT using the alias name Submit.
     * @return the SUBMIT
     */
    public String getSubmit() {
        return (String) getAttributeInternal(SUBMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT using the alias name Submit.
     * @param value value to set the SUBMIT
     */
    public void setSubmit(String value) {
        setAttributeInternal(SUBMIT, value);
    }

    /**
     * Gets the attribute value for SYMPTOM_DATE using the alias name SymptomDate.
     * @return the SYMPTOM_DATE
     */
    public Date getSymptomDate() {
        return (Date) getAttributeInternal(SYMPTOMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SYMPTOM_DATE using the alias name SymptomDate.
     * @param value value to set the SYMPTOM_DATE
     */
    public void setSymptomDate(Date value) {
        setAttributeInternal(SYMPTOMDATE, value);
    }

    /**
     * Gets the attribute value for EBS_CUSTOMER_ID using the alias name EbsCustomerId.
     * @return the EBS_CUSTOMER_ID
     */
    public String getEbsCustomerId() {
        return (String) getAttributeInternal(EBSCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_CUSTOMER_ID using the alias name EbsCustomerId.
     * @param value value to set the EBS_CUSTOMER_ID
     */
    public void setEbsCustomerId(String value) {
        setAttributeInternal(EBSCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for EBS_SALESPERSON_ID using the alias name EbsSalespersonId.
     * @return the EBS_SALESPERSON_ID
     */
    public String getEbsSalespersonId() {
        return (String) getAttributeInternal(EBSSALESPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_SALESPERSON_ID using the alias name EbsSalespersonId.
     * @param value value to set the EBS_SALESPERSON_ID
     */
    public void setEbsSalespersonId(String value) {
        setAttributeInternal(EBSSALESPERSONID, value);
    }

    /**
     * Gets the attribute value for EBS_LOCATION_ID using the alias name EbsLocationId.
     * @return the EBS_LOCATION_ID
     */
    public String getEbsLocationId() {
        return (String) getAttributeInternal(EBSLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_LOCATION_ID using the alias name EbsLocationId.
     * @param value value to set the EBS_LOCATION_ID
     */
    public void setEbsLocationId(String value) {
        setAttributeInternal(EBSLOCATIONID, value);
    }

    /**
     * Gets the attribute value for EBS_STORE_ID using the alias name EbsStoreId.
     * @return the EBS_STORE_ID
     */
    public String getEbsStoreId() {
        return (String) getAttributeInternal(EBSSTOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_STORE_ID using the alias name EbsStoreId.
     * @param value value to set the EBS_STORE_ID
     */
    public void setEbsStoreId(String value) {
        setAttributeInternal(EBSSTOREID, value);
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for CONSIGNMENT_NO using the alias name ConsignmentNo.
     * @return the CONSIGNMENT_NO
     */
    public String getConsignmentNo() {
        return (String) getAttributeInternal(CONSIGNMENTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONSIGNMENT_NO using the alias name ConsignmentNo.
     * @param value value to set the CONSIGNMENT_NO
     */
    public void setConsignmentNo(String value) {
        setAttributeInternal(CONSIGNMENTNO, value);
    }

    /**
     * Gets the attribute value for SALESRETSEQ using the alias name Salesretseq.
     * @return the SALESRETSEQ
     */
    public Integer getSalesretseq() {
        return (Integer) getAttributeInternal(SALESRETSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESRETSEQ using the alias name Salesretseq.
     * @param value value to set the SALESRETSEQ
     */
    public void setSalesretseq(Integer value) {
        setAttributeInternal(SALESRETSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @return the TXT_CUSTOMER_NAME
     */
    public String gettxtCustomerName() {
        return (String) getAttributeInternal(TXTCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_CUSTOMER_NAME using the alias name txtCustomerName.
     * @param value value to set the TXT_CUSTOMER_NAME
     */
    public void settxtCustomerName(String value) {
        setAttributeInternal(TXTCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @return the TXT_SALES_PERSON_NAME
     */
    public String gettxtSalesPersonName() {
        return (String) getAttributeInternal(TXTSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SALES_PERSON_NAME using the alias name txtSalesPersonName.
     * @param value value to set the TXT_SALES_PERSON_NAME
     */
    public void settxtSalesPersonName(String value) {
        setAttributeInternal(TXTSALESPERSONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @return the TXT_SUPPLIER_NAME
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @param value value to set the TXT_SUPPLIER_NAME
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @return the TXT_STORE_NAME
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @param value value to set the TXT_STORE_NAME
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for MANUAL_REF_NO using the alias name ManualRefNo.
     * @return the MANUAL_REF_NO
     */
    public String getManualRefNo() {
        return (String) getAttributeInternal(MANUALREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for MANUAL_REF_NO using the alias name ManualRefNo.
     * @param value value to set the MANUAL_REF_NO
     */
    public void setManualRefNo(String value) {
        setAttributeInternal(MANUALREFNO, value);
    }

    /**
     * Gets the attribute value for DIVID using the alias name Divid.
     * @return the DIVID
     */
    public String getDivid() {
        return (String) getAttributeInternal(DIVID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVID using the alias name Divid.
     * @param value value to set the DIVID
     */
    public void setDivid(String value) {
        setAttributeInternal(DIVID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SoSalesReturnLinesView.
     */
    public RowIterator getSoSalesReturnLinesView() {
        return (RowIterator) getAttributeInternal(SOSALESRETURNLINESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrimeiView.
     */
    public RowIterator getSrimeiView() {
        return (RowIterator) getAttributeInternal(SRIMEIVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllCustomersView.
     */
    public Row getAllCustomersView() {
        return (Row) getAttributeInternal(ALLCUSTOMERSVIEW);
    }

    /**
     * Sets the master-detail link AllCustomersView between this object and <code>value</code>.
     */
    public void setAllCustomersView(Row value) {
        setAttributeInternal(ALLCUSTOMERSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SoSalesPersonsView.
     */
    public Row getSoSalesPersonsView() {
        return (Row) getAttributeInternal(SOSALESPERSONSVIEW);
    }

    /**
     * Sets the master-detail link SoSalesPersonsView between this object and <code>value</code>.
     */
    public void setSoSalesPersonsView(Row value) {
        setAttributeInternal(SOSALESPERSONSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PuSuppliersView.
     */
    public Row getPuSuppliersView() {
        return (Row) getAttributeInternal(PUSUPPLIERSVIEW);
    }

    /**
     * Sets the master-detail link PuSuppliersView between this object and <code>value</code>.
     */
    public void setPuSuppliersView(Row value) {
        setAttributeInternal(PUSUPPLIERSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllStoresView.
     */
    public Row getAllStoresView() {
        return (Row) getAttributeInternal(ALLSTORESVIEW);
    }

    /**
     * Sets the master-detail link AllStoresView between this object and <code>value</code>.
     */
    public void setAllStoresView(Row value) {
        setAttributeInternal(ALLSTORESVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSretCategoryView.
     */
    public RowSet getAccSretCategoryView() {
        return (RowSet) getAttributeInternal(ACCSRETCATEGORYVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomersView.
     */
    public RowSet getAccAllCustomersView() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsView.
     */
    public RowSet getAccSoSalesPersonsView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSoSalesPersonsDefView.
     */
    public RowSet getAccSoSalesPersonsDefView() {
        return (RowSet) getAttributeInternal(ACCSOSALESPERSONSDEFVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllCustomerSalespersonPid.
     */
    public RowSet getAccAllCustomerSalespersonPid() {
        return (RowSet) getAttributeInternal(ACCALLCUSTOMERSALESPERSONPID);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccPuSuppliersView.
     */
    public RowSet getAccPuSuppliersView() {
        return (RowSet) getAttributeInternal(ACCPUSUPPLIERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresView.
     */
    public RowSet getAccAllStoresView() {
        return (RowSet) getAttributeInternal(ACCALLSTORESVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWYesNoQVO.
     */
    public RowSet getAccVWYesNoQVO() {
        return (RowSet) getAttributeInternal(ACCVWYESNOQVO);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

