package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 14 22:08:01 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoSalesReturnLinesViewImpl extends ERPSolGlobalsViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SoSalesReturnLinesViewImpl() {
    }
}

