package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolscm.erpsolscmmodel.erpsolscmeo.SoSalesReturnLinesImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 14 22:08:00 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoSalesReturnLinesViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_SOSALESRETURNLINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Salesretid,
        Rlineno,
        Uomsid,
        Productid,
        ModelNo,
        Quantity,
        StdUnitPrice,
        ActUnitPriceBcurr,
        ActUnitPriceFcurr,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        IssueDocNo,
        UnitCost,
        Invoiceid,
        Lineno,
        DiscountAmountBc,
        StAmountBc,
        RetQty,
        RetDiscountAmount,
        RetStAmount,
        ReceivedQty,
        RetStaxp,
        RemQty,
        SedAmountBc,
        RetSedAmount,
        RetSedp,
        ExtraTaxAmountBc,
        RetExtraTaxAmount,
        RetExtraTaxp,
        Srdetlid,
        SalesQty,
        AddDiscountAmount,
        DefaultDiscountAmount,
        FcurrRetDiscountAmount,
        FcurrAddDiscountAmount,
        FcurrDefaultDiscountAmount,
        PerUnitLandedCost,
        Incentive,
        ScratchCard,
        GiftSchm,
        EbsItemid,
        Salesretseq,
        Salesreturnlinseq,
        txtGrossAmount,
        txtNetAmount,
        txtRetDiscountAmount,
        txtAddDiscountAmount,
        txtTotalDiscount,
        SrimeiView,
        InItemsView,
        SoSalesReturnView,
        AccInItemsView,
        AccVwFuncGetItemRateByLocDate,
        AccVwFuncGetItemDiscountByLocationReturn,
        AccVwFuncGetItemAdditionalDiscount;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESRETID = AttributesEnum.Salesretid.index();
    public static final int RLINENO = AttributesEnum.Rlineno.index();
    public static final int UOMSID = AttributesEnum.Uomsid.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int MODELNO = AttributesEnum.ModelNo.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int STDUNITPRICE = AttributesEnum.StdUnitPrice.index();
    public static final int ACTUNITPRICEBCURR = AttributesEnum.ActUnitPriceBcurr.index();
    public static final int ACTUNITPRICEFCURR = AttributesEnum.ActUnitPriceFcurr.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ISSUEDOCNO = AttributesEnum.IssueDocNo.index();
    public static final int UNITCOST = AttributesEnum.UnitCost.index();
    public static final int INVOICEID = AttributesEnum.Invoiceid.index();
    public static final int LINENO = AttributesEnum.Lineno.index();
    public static final int DISCOUNTAMOUNTBC = AttributesEnum.DiscountAmountBc.index();
    public static final int STAMOUNTBC = AttributesEnum.StAmountBc.index();
    public static final int RETQTY = AttributesEnum.RetQty.index();
    public static final int RETDISCOUNTAMOUNT = AttributesEnum.RetDiscountAmount.index();
    public static final int RETSTAMOUNT = AttributesEnum.RetStAmount.index();
    public static final int RECEIVEDQTY = AttributesEnum.ReceivedQty.index();
    public static final int RETSTAXP = AttributesEnum.RetStaxp.index();
    public static final int REMQTY = AttributesEnum.RemQty.index();
    public static final int SEDAMOUNTBC = AttributesEnum.SedAmountBc.index();
    public static final int RETSEDAMOUNT = AttributesEnum.RetSedAmount.index();
    public static final int RETSEDP = AttributesEnum.RetSedp.index();
    public static final int EXTRATAXAMOUNTBC = AttributesEnum.ExtraTaxAmountBc.index();
    public static final int RETEXTRATAXAMOUNT = AttributesEnum.RetExtraTaxAmount.index();
    public static final int RETEXTRATAXP = AttributesEnum.RetExtraTaxp.index();
    public static final int SRDETLID = AttributesEnum.Srdetlid.index();
    public static final int SALESQTY = AttributesEnum.SalesQty.index();
    public static final int ADDDISCOUNTAMOUNT = AttributesEnum.AddDiscountAmount.index();
    public static final int DEFAULTDISCOUNTAMOUNT = AttributesEnum.DefaultDiscountAmount.index();
    public static final int FCURRRETDISCOUNTAMOUNT = AttributesEnum.FcurrRetDiscountAmount.index();
    public static final int FCURRADDDISCOUNTAMOUNT = AttributesEnum.FcurrAddDiscountAmount.index();
    public static final int FCURRDEFAULTDISCOUNTAMOUNT = AttributesEnum.FcurrDefaultDiscountAmount.index();
    public static final int PERUNITLANDEDCOST = AttributesEnum.PerUnitLandedCost.index();
    public static final int INCENTIVE = AttributesEnum.Incentive.index();
    public static final int SCRATCHCARD = AttributesEnum.ScratchCard.index();
    public static final int GIFTSCHM = AttributesEnum.GiftSchm.index();
    public static final int EBSITEMID = AttributesEnum.EbsItemid.index();
    public static final int SALESRETSEQ = AttributesEnum.Salesretseq.index();
    public static final int SALESRETURNLINSEQ = AttributesEnum.Salesreturnlinseq.index();
    public static final int TXTGROSSAMOUNT = AttributesEnum.txtGrossAmount.index();
    public static final int TXTNETAMOUNT = AttributesEnum.txtNetAmount.index();
    public static final int TXTRETDISCOUNTAMOUNT = AttributesEnum.txtRetDiscountAmount.index();
    public static final int TXTADDDISCOUNTAMOUNT = AttributesEnum.txtAddDiscountAmount.index();
    public static final int TXTTOTALDISCOUNT = AttributesEnum.txtTotalDiscount.index();
    public static final int SRIMEIVIEW = AttributesEnum.SrimeiView.index();
    public static final int INITEMSVIEW = AttributesEnum.InItemsView.index();
    public static final int SOSALESRETURNVIEW = AttributesEnum.SoSalesReturnView.index();
    public static final int ACCINITEMSVIEW = AttributesEnum.AccInItemsView.index();
    public static final int ACCVWFUNCGETITEMRATEBYLOCDATE = AttributesEnum.AccVwFuncGetItemRateByLocDate.index();
    public static final int ACCVWFUNCGETITEMDISCOUNTBYLOCATIONRETURN =
        AttributesEnum.AccVwFuncGetItemDiscountByLocationReturn.index();
    public static final int ACCVWFUNCGETITEMADDITIONALDISCOUNT =
        AttributesEnum.AccVwFuncGetItemAdditionalDiscount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoSalesReturnLinesViewRowImpl() {
    }

    /**
     * Gets SoSalesReturnLines entity object.
     * @return the SoSalesReturnLines
     */
    public SoSalesReturnLinesImpl getSoSalesReturnLines() {
        return (SoSalesReturnLinesImpl) getEntity(ENTITY_SOSALESRETURNLINES);
    }

    /**
     * Gets the attribute value for SALESRETID using the alias name Salesretid.
     * @return the SALESRETID
     */
    public String getSalesretid() {
        return (String) getAttributeInternal(SALESRETID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESRETID using the alias name Salesretid.
     * @param value value to set the SALESRETID
     */
    public void setSalesretid(String value) {
        setAttributeInternal(SALESRETID, value);
    }

    /**
     * Gets the attribute value for RLINENO using the alias name Rlineno.
     * @return the RLINENO
     */
    public Integer getRlineno() {
        return (Integer) getAttributeInternal(RLINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for RLINENO using the alias name Rlineno.
     * @param value value to set the RLINENO
     */
    public void setRlineno(Integer value) {
        setAttributeInternal(RLINENO, value);
    }

    /**
     * Gets the attribute value for UOMSID using the alias name Uomsid.
     * @return the UOMSID
     */
    public String getUomsid() {
        return (String) getAttributeInternal(UOMSID);
    }

    /**
     * Sets <code>value</code> as attribute value for UOMSID using the alias name Uomsid.
     * @param value value to set the UOMSID
     */
    public void setUomsid(String value) {
        setAttributeInternal(UOMSID, value);
    }

    /**
     * Gets the attribute value for PRODUCTID using the alias name Productid.
     * @return the PRODUCTID
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTID using the alias name Productid.
     * @param value value to set the PRODUCTID
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
        System.out.println(getSoSalesReturnView().getAttribute("ReturnDate"));
        System.out.println(value);
        System.out.println(getSoSalesReturnView().getAttribute("Locationid"));
        try{
            getAccVwFuncGetItemRateByLocDate().setNamedWhereClauseParam("P_ADF_DATE", getSoSalesReturnView().getAttribute("ReturnDate"));
            getAccVwFuncGetItemRateByLocDate().setNamedWhereClauseParam("P_ADF_ITEMID", value);
            getAccVwFuncGetItemRateByLocDate().setNamedWhereClauseParam("P_ADF_LOCATIONID", getSoSalesReturnView().getAttribute("Locationid"));
            getAccVwFuncGetItemRateByLocDate().executeQuery();
            setActUnitPriceFcurr((Integer)getAccVwFuncGetItemRateByLocDate().first().getAttribute("Rate")) ;
            setActUnitPriceBcurr((Integer)(getAccVwFuncGetItemRateByLocDate().first().getAttribute("Rate"))) ;
            }
            catch(Exception exc) {
            setActUnitPriceBcurr(0) ;
            setActUnitPriceFcurr(0);
            exc.printStackTrace();
            }  
        try{
            System.out.println("a");
            getAccVwFuncGetItemDiscountByLocationReturn().setNamedWhereClauseParam("P_ADF_DATE", getSoSalesReturnView().getAttribute("ReturnDate"));
                System.out.println("b");
            getAccVwFuncGetItemDiscountByLocationReturn().setNamedWhereClauseParam("P_ADF_ITEMID", value);
                System.out.println("d");
            getAccVwFuncGetItemDiscountByLocationReturn().setNamedWhereClauseParam("P_ADF_LOCATIONID", getSoSalesReturnView().getAttribute("Locationid"));
                System.out.println("e");
            getAccVwFuncGetItemDiscountByLocationReturn().executeQuery();
                System.out.println("f");
            BigDecimal erpsoldiscount= ((BigDecimal)getAccVwFuncGetItemDiscountByLocationReturn().first().getAttribute("Discount")) ;
               
            erpsoldiscount=  (new BigDecimal(getActUnitPriceFcurr()).multiply(erpsoldiscount)).divide(new BigDecimal(100)); ;
            setRetDiscountAmount(erpsoldiscount.intValue());
//                erpsoldiscount=getActUnitPriceFcurr().multiply(erpsoldiscount);
            }
            catch(Exception exc) {
            setActUnitPriceBcurr(0 );
            setActUnitPriceFcurr(0);
            exc.printStackTrace();
            }         
        
        try{
            System.out.println("a");
            getAccVwFuncGetItemAdditionalDiscount().setNamedWhereClauseParam("P_ADF_DATE", getSoSalesReturnView().getAttribute("ReturnDate"));
                System.out.println("b");
            getAccVwFuncGetItemAdditionalDiscount().setNamedWhereClauseParam("P_ADF_ITEMID", value);
                System.out.println("d");
            getAccVwFuncGetItemAdditionalDiscount().setNamedWhereClauseParam("P_ADF_LOCATIONID", getSoSalesReturnView().getAttribute("Locationid"));
                System.out.println("e");
            getAccVwFuncGetItemAdditionalDiscount().executeQuery();
                System.out.println("f");
            setAddDiscountAmount(Integer.parseInt(getAccVwFuncGetItemAdditionalDiscount().first().getAttribute("AdditionalDisAmount").toString()));
            setFcurrAddDiscountAmount(getAddDiscountAmount());
        //                erpsoldiscount=getActUnitPriceFcurr().multiply(erpsoldiscount);
            }
            catch(Exception exc) {
            setAddDiscountAmount(0 );
            setFcurrAddDiscountAmount(0);
            exc.printStackTrace();
            }         
    }

    /**
     * Gets the attribute value for MODEL_NO using the alias name ModelNo.
     * @return the MODEL_NO
     */
    public String getModelNo() {
        return (String) getAttributeInternal(MODELNO);
    }

    /**
     * Sets <code>value</code> as attribute value for MODEL_NO using the alias name ModelNo.
     * @param value value to set the MODEL_NO
     */
    public void setModelNo(String value) {
        setAttributeInternal(MODELNO, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Integer getQuantity() {
        return (Integer) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Integer value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for STD_UNIT_PRICE using the alias name StdUnitPrice.
     * @return the STD_UNIT_PRICE
     */
    public BigDecimal getStdUnitPrice() {
        return (BigDecimal) getAttributeInternal(STDUNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for STD_UNIT_PRICE using the alias name StdUnitPrice.
     * @param value value to set the STD_UNIT_PRICE
     */
    public void setStdUnitPrice(BigDecimal value) {
        setAttributeInternal(STDUNITPRICE, value);
    }

    /**
     * Gets the attribute value for ACT_UNIT_PRICE_BCURR using the alias name ActUnitPriceBcurr.
     * @return the ACT_UNIT_PRICE_BCURR
     */
    public Integer getActUnitPriceBcurr() {
        return (Integer) getAttributeInternal(ACTUNITPRICEBCURR);
    }

    /**
     * Sets <code>value</code> as attribute value for ACT_UNIT_PRICE_BCURR using the alias name ActUnitPriceBcurr.
     * @param value value to set the ACT_UNIT_PRICE_BCURR
     */
    public void setActUnitPriceBcurr(Integer value) {
        setAttributeInternal(ACTUNITPRICEBCURR, value);
    }

    /**
     * Gets the attribute value for ACT_UNIT_PRICE_FCURR using the alias name ActUnitPriceFcurr.
     * @return the ACT_UNIT_PRICE_FCURR
     */
    public Integer getActUnitPriceFcurr() {
        return (Integer) getAttributeInternal(ACTUNITPRICEFCURR);
    }

    /**
     * Sets <code>value</code> as attribute value for ACT_UNIT_PRICE_FCURR using the alias name ActUnitPriceFcurr.
     * @param value value to set the ACT_UNIT_PRICE_FCURR
     */
    public void setActUnitPriceFcurr(Integer value) {
        setAttributeInternal(ACTUNITPRICEFCURR, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ISSUE_DOC_NO using the alias name IssueDocNo.
     * @return the ISSUE_DOC_NO
     */
    public String getIssueDocNo() {
        return (String) getAttributeInternal(ISSUEDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUE_DOC_NO using the alias name IssueDocNo.
     * @param value value to set the ISSUE_DOC_NO
     */
    public void setIssueDocNo(String value) {
        setAttributeInternal(ISSUEDOCNO, value);
    }

    /**
     * Gets the attribute value for UNIT_COST using the alias name UnitCost.
     * @return the UNIT_COST
     */
    public BigDecimal getUnitCost() {
        return (BigDecimal) getAttributeInternal(UNITCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_COST using the alias name UnitCost.
     * @param value value to set the UNIT_COST
     */
    public void setUnitCost(BigDecimal value) {
        setAttributeInternal(UNITCOST, value);
    }

    /**
     * Gets the attribute value for INVOICEID using the alias name Invoiceid.
     * @return the INVOICEID
     */
    public String getInvoiceid() {
        return (String) getAttributeInternal(INVOICEID);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICEID using the alias name Invoiceid.
     * @param value value to set the INVOICEID
     */
    public void setInvoiceid(String value) {
        setAttributeInternal(INVOICEID, value);
    }

    /**
     * Gets the attribute value for LINENO using the alias name Lineno.
     * @return the LINENO
     */
    public Integer getLineno() {
        return (Integer) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINENO using the alias name Lineno.
     * @param value value to set the LINENO
     */
    public void setLineno(Integer value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for DISCOUNT_AMOUNT_BC using the alias name DiscountAmountBc.
     * @return the DISCOUNT_AMOUNT_BC
     */
    public Integer getDiscountAmountBc() {
        return (Integer) getAttributeInternal(DISCOUNTAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT_AMOUNT_BC using the alias name DiscountAmountBc.
     * @param value value to set the DISCOUNT_AMOUNT_BC
     */
    public void setDiscountAmountBc(Integer value) {
        setAttributeInternal(DISCOUNTAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for ST_AMOUNT_BC using the alias name StAmountBc.
     * @return the ST_AMOUNT_BC
     */
    public BigDecimal getStAmountBc() {
        return (BigDecimal) getAttributeInternal(STAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as attribute value for ST_AMOUNT_BC using the alias name StAmountBc.
     * @param value value to set the ST_AMOUNT_BC
     */
    public void setStAmountBc(BigDecimal value) {
        setAttributeInternal(STAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for RET_QTY using the alias name RetQty.
     * @return the RET_QTY
     */
    public Integer getRetQty() {
        return (Integer) getAttributeInternal(RETQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_QTY using the alias name RetQty.
     * @param value value to set the RET_QTY
     */
    public void setRetQty(Integer value) {
        setAttributeInternal(RETQTY, value);
    }

    /**
     * Gets the attribute value for RET_DISCOUNT_AMOUNT using the alias name RetDiscountAmount.
     * @return the RET_DISCOUNT_AMOUNT
     */
    public Integer getRetDiscountAmount() {
        return (Integer) getAttributeInternal(RETDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_DISCOUNT_AMOUNT using the alias name RetDiscountAmount.
     * @param value value to set the RET_DISCOUNT_AMOUNT
     */
    public void setRetDiscountAmount(Integer value) {
        setAttributeInternal(RETDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for RET_ST_AMOUNT using the alias name RetStAmount.
     * @return the RET_ST_AMOUNT
     */
    public BigDecimal getRetStAmount() {
        return (BigDecimal) getAttributeInternal(RETSTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_ST_AMOUNT using the alias name RetStAmount.
     * @param value value to set the RET_ST_AMOUNT
     */
    public void setRetStAmount(BigDecimal value) {
        setAttributeInternal(RETSTAMOUNT, value);
    }

    /**
     * Gets the attribute value for RECEIVED_QTY using the alias name ReceivedQty.
     * @return the RECEIVED_QTY
     */
    public Integer getReceivedQty() {
        return (Integer) getAttributeInternal(RECEIVEDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVED_QTY using the alias name ReceivedQty.
     * @param value value to set the RECEIVED_QTY
     */
    public void setReceivedQty(Integer value) {
        setAttributeInternal(RECEIVEDQTY, value);
    }

    /**
     * Gets the attribute value for RET_STAXP using the alias name RetStaxp.
     * @return the RET_STAXP
     */
    public BigDecimal getRetStaxp() {
        return (BigDecimal) getAttributeInternal(RETSTAXP);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_STAXP using the alias name RetStaxp.
     * @param value value to set the RET_STAXP
     */
    public void setRetStaxp(BigDecimal value) {
        setAttributeInternal(RETSTAXP, value);
    }

    /**
     * Gets the attribute value for REM_QTY using the alias name RemQty.
     * @return the REM_QTY
     */
    public BigDecimal getRemQty() {
        return (BigDecimal) getAttributeInternal(REMQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for REM_QTY using the alias name RemQty.
     * @param value value to set the REM_QTY
     */
    public void setRemQty(BigDecimal value) {
        setAttributeInternal(REMQTY, value);
    }

    /**
     * Gets the attribute value for SED_AMOUNT_BC using the alias name SedAmountBc.
     * @return the SED_AMOUNT_BC
     */
    public BigDecimal getSedAmountBc() {
        return (BigDecimal) getAttributeInternal(SEDAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as attribute value for SED_AMOUNT_BC using the alias name SedAmountBc.
     * @param value value to set the SED_AMOUNT_BC
     */
    public void setSedAmountBc(BigDecimal value) {
        setAttributeInternal(SEDAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for RET_SED_AMOUNT using the alias name RetSedAmount.
     * @return the RET_SED_AMOUNT
     */
    public BigDecimal getRetSedAmount() {
        return (BigDecimal) getAttributeInternal(RETSEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_SED_AMOUNT using the alias name RetSedAmount.
     * @param value value to set the RET_SED_AMOUNT
     */
    public void setRetSedAmount(BigDecimal value) {
        setAttributeInternal(RETSEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for RET_SEDP using the alias name RetSedp.
     * @return the RET_SEDP
     */
    public BigDecimal getRetSedp() {
        return (BigDecimal) getAttributeInternal(RETSEDP);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_SEDP using the alias name RetSedp.
     * @param value value to set the RET_SEDP
     */
    public void setRetSedp(BigDecimal value) {
        setAttributeInternal(RETSEDP, value);
    }

    /**
     * Gets the attribute value for EXTRA_TAX_AMOUNT_BC using the alias name ExtraTaxAmountBc.
     * @return the EXTRA_TAX_AMOUNT_BC
     */
    public Integer getExtraTaxAmountBc() {
        return (Integer) getAttributeInternal(EXTRATAXAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTRA_TAX_AMOUNT_BC using the alias name ExtraTaxAmountBc.
     * @param value value to set the EXTRA_TAX_AMOUNT_BC
     */
    public void setExtraTaxAmountBc(Integer value) {
        setAttributeInternal(EXTRATAXAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for RET_EXTRA_TAX_AMOUNT using the alias name RetExtraTaxAmount.
     * @return the RET_EXTRA_TAX_AMOUNT
     */
    public BigDecimal getRetExtraTaxAmount() {
        return (BigDecimal) getAttributeInternal(RETEXTRATAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_EXTRA_TAX_AMOUNT using the alias name RetExtraTaxAmount.
     * @param value value to set the RET_EXTRA_TAX_AMOUNT
     */
    public void setRetExtraTaxAmount(BigDecimal value) {
        setAttributeInternal(RETEXTRATAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for RET_EXTRA_TAXP using the alias name RetExtraTaxp.
     * @return the RET_EXTRA_TAXP
     */
    public BigDecimal getRetExtraTaxp() {
        return (BigDecimal) getAttributeInternal(RETEXTRATAXP);
    }

    /**
     * Sets <code>value</code> as attribute value for RET_EXTRA_TAXP using the alias name RetExtraTaxp.
     * @param value value to set the RET_EXTRA_TAXP
     */
    public void setRetExtraTaxp(BigDecimal value) {
        setAttributeInternal(RETEXTRATAXP, value);
    }

    /**
     * Gets the attribute value for SRDETLID using the alias name Srdetlid.
     * @return the SRDETLID
     */
    public String getSrdetlid() {
        return (String) getAttributeInternal(SRDETLID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRDETLID using the alias name Srdetlid.
     * @param value value to set the SRDETLID
     */
    public void setSrdetlid(String value) {
        setAttributeInternal(SRDETLID, value);
    }

    /**
     * Gets the attribute value for SALES_QTY using the alias name SalesQty.
     * @return the SALES_QTY
     */
    public Integer getSalesQty() {
        return (Integer) getAttributeInternal(SALESQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_QTY using the alias name SalesQty.
     * @param value value to set the SALES_QTY
     */
    public void setSalesQty(Integer value) {
        setAttributeInternal(SALESQTY, value);
    }

    /**
     * Gets the attribute value for ADD_DISCOUNT_AMOUNT using the alias name AddDiscountAmount.
     * @return the ADD_DISCOUNT_AMOUNT
     */
    public Integer getAddDiscountAmount() {
        return (Integer) getAttributeInternal(ADDDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ADD_DISCOUNT_AMOUNT using the alias name AddDiscountAmount.
     * @param value value to set the ADD_DISCOUNT_AMOUNT
     */
    public void setAddDiscountAmount(Integer value) {
        setAttributeInternal(ADDDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for DEFAULT_DISCOUNT_AMOUNT using the alias name DefaultDiscountAmount.
     * @return the DEFAULT_DISCOUNT_AMOUNT
     */
    public Integer getDefaultDiscountAmount() {
        return (Integer) getAttributeInternal(DEFAULTDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEFAULT_DISCOUNT_AMOUNT using the alias name DefaultDiscountAmount.
     * @param value value to set the DEFAULT_DISCOUNT_AMOUNT
     */
    public void setDefaultDiscountAmount(Integer value) {
        setAttributeInternal(DEFAULTDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_RET_DISCOUNT_AMOUNT using the alias name FcurrRetDiscountAmount.
     * @return the FCURR_RET_DISCOUNT_AMOUNT
     */
    public Integer getFcurrRetDiscountAmount() {
        return (Integer) getAttributeInternal(FCURRRETDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_RET_DISCOUNT_AMOUNT using the alias name FcurrRetDiscountAmount.
     * @param value value to set the FCURR_RET_DISCOUNT_AMOUNT
     */
    public void setFcurrRetDiscountAmount(Integer value) {
        setAttributeInternal(FCURRRETDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_ADD_DISCOUNT_AMOUNT using the alias name FcurrAddDiscountAmount.
     * @return the FCURR_ADD_DISCOUNT_AMOUNT
     */
    public Integer getFcurrAddDiscountAmount() {
        return (Integer) getAttributeInternal(FCURRADDDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_ADD_DISCOUNT_AMOUNT using the alias name FcurrAddDiscountAmount.
     * @param value value to set the FCURR_ADD_DISCOUNT_AMOUNT
     */
    public void setFcurrAddDiscountAmount(Integer value) {
        setAttributeInternal(FCURRADDDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for FCURR_DEFAULT_DISCOUNT_AMOUNT using the alias name FcurrDefaultDiscountAmount.
     * @return the FCURR_DEFAULT_DISCOUNT_AMOUNT
     */
    public Integer getFcurrDefaultDiscountAmount() {
        return (Integer) getAttributeInternal(FCURRDEFAULTDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FCURR_DEFAULT_DISCOUNT_AMOUNT using the alias name FcurrDefaultDiscountAmount.
     * @param value value to set the FCURR_DEFAULT_DISCOUNT_AMOUNT
     */
    public void setFcurrDefaultDiscountAmount(Integer value) {
        setAttributeInternal(FCURRDEFAULTDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for PER_UNIT_LANDED_COST using the alias name PerUnitLandedCost.
     * @return the PER_UNIT_LANDED_COST
     */
    public Integer getPerUnitLandedCost() {
        return (Integer) getAttributeInternal(PERUNITLANDEDCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for PER_UNIT_LANDED_COST using the alias name PerUnitLandedCost.
     * @param value value to set the PER_UNIT_LANDED_COST
     */
    public void setPerUnitLandedCost(Integer value) {
        setAttributeInternal(PERUNITLANDEDCOST, value);
    }

    /**
     * Gets the attribute value for INCENTIVE using the alias name Incentive.
     * @return the INCENTIVE
     */
    public Integer getIncentive() {
        return (Integer) getAttributeInternal(INCENTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for INCENTIVE using the alias name Incentive.
     * @param value value to set the INCENTIVE
     */
    public void setIncentive(Integer value) {
        setAttributeInternal(INCENTIVE, value);
    }

    /**
     * Gets the attribute value for SCRATCH_CARD using the alias name ScratchCard.
     * @return the SCRATCH_CARD
     */
    public BigDecimal getScratchCard() {
        return (BigDecimal) getAttributeInternal(SCRATCHCARD);
    }

    /**
     * Sets <code>value</code> as attribute value for SCRATCH_CARD using the alias name ScratchCard.
     * @param value value to set the SCRATCH_CARD
     */
    public void setScratchCard(BigDecimal value) {
        setAttributeInternal(SCRATCHCARD, value);
    }

    /**
     * Gets the attribute value for GIFT_SCHM using the alias name GiftSchm.
     * @return the GIFT_SCHM
     */
    public Integer getGiftSchm() {
        return (Integer) getAttributeInternal(GIFTSCHM);
    }

    /**
     * Sets <code>value</code> as attribute value for GIFT_SCHM using the alias name GiftSchm.
     * @param value value to set the GIFT_SCHM
     */
    public void setGiftSchm(Integer value) {
        setAttributeInternal(GIFTSCHM, value);
    }

    /**
     * Gets the attribute value for EBS_ITEMID using the alias name EbsItemid.
     * @return the EBS_ITEMID
     */
    public String getEbsItemid() {
        return (String) getAttributeInternal(EBSITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for EBS_ITEMID using the alias name EbsItemid.
     * @param value value to set the EBS_ITEMID
     */
    public void setEbsItemid(String value) {
        setAttributeInternal(EBSITEMID, value);
    }

    /**
     * Gets the attribute value for SALESRETSEQ using the alias name Salesretseq.
     * @return the SALESRETSEQ
     */
    public Integer getSalesretseq() {
        return (Integer) getAttributeInternal(SALESRETSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESRETSEQ using the alias name Salesretseq.
     * @param value value to set the SALESRETSEQ
     */
    public void setSalesretseq(Integer value) {
        setAttributeInternal(SALESRETSEQ, value);
    }

    /**
     * Gets the attribute value for SALESRETURNLINSEQ using the alias name Salesreturnlinseq.
     * @return the SALESRETURNLINSEQ
     */
    public Integer getSalesreturnlinseq() {
        return (Integer) getAttributeInternal(SALESRETURNLINSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESRETURNLINSEQ using the alias name Salesreturnlinseq.
     * @param value value to set the SALESRETURNLINSEQ
     */
    public void setSalesreturnlinseq(Integer value) {
        setAttributeInternal(SALESRETURNLINSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_GROSS_AMOUNT using the alias name txtGrossAmount.
     * @return the TXT_GROSS_AMOUNT
     */
    public Integer gettxtGrossAmount() {
        return (Integer) getAttributeInternal(TXTGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_GROSS_AMOUNT using the alias name txtGrossAmount.
     * @param value value to set the TXT_GROSS_AMOUNT
     */
    public void settxtGrossAmount(Integer value) {
        setAttributeInternal(TXTGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_NET_AMOUNT using the alias name txtNetAmount.
     * @return the TXT_NET_AMOUNT
     */
    public Integer gettxtNetAmount() {
        return (Integer) getAttributeInternal(TXTNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_NET_AMOUNT using the alias name txtNetAmount.
     * @param value value to set the TXT_NET_AMOUNT
     */
    public void settxtNetAmount(Integer value) {
        setAttributeInternal(TXTNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_RET_DISCOUNT_AMOUNT using the alias name txtRetDiscountAmount.
     * @return the TXT_RET_DISCOUNT_AMOUNT
     */
    public Integer gettxtRetDiscountAmount() {
        return (Integer) getAttributeInternal(TXTRETDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_RET_DISCOUNT_AMOUNT using the alias name txtRetDiscountAmount.
     * @param value value to set the TXT_RET_DISCOUNT_AMOUNT
     */
    public void settxtRetDiscountAmount(Integer value) {
        setAttributeInternal(TXTRETDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_ADD_DISCOUNT_AMOUNT using the alias name txtAddDiscountAmount.
     * @return the TXT_ADD_DISCOUNT_AMOUNT
     */
    public Integer gettxtAddDiscountAmount() {
        return (Integer) getAttributeInternal(TXTADDDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ADD_DISCOUNT_AMOUNT using the alias name txtAddDiscountAmount.
     * @param value value to set the TXT_ADD_DISCOUNT_AMOUNT
     */
    public void settxtAddDiscountAmount(Integer value) {
        setAttributeInternal(TXTADDDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_TOTAL_DISCOUNT using the alias name txtTotalDiscount.
     * @return the TXT_TOTAL_DISCOUNT
     */
    public BigDecimal gettxtTotalDiscount() {
        return (BigDecimal) getAttributeInternal(TXTTOTALDISCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TOTAL_DISCOUNT using the alias name txtTotalDiscount.
     * @param value value to set the TXT_TOTAL_DISCOUNT
     */
    public void settxtTotalDiscount(BigDecimal value) {
        setAttributeInternal(TXTTOTALDISCOUNT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrimeiView.
     */
    public RowIterator getSrimeiView() {
        return (RowIterator) getAttributeInternal(SRIMEIVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InItemsView.
     */
    public Row getInItemsView() {
        return (Row) getAttributeInternal(INITEMSVIEW);
    }

    /**
     * Sets the master-detail link InItemsView between this object and <code>value</code>.
     */
    public void setInItemsView(Row value) {
        setAttributeInternal(INITEMSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SoSalesReturnView.
     */
    public Row getSoSalesReturnView() {
        return (Row) getAttributeInternal(SOSALESRETURNVIEW);
    }

    /**
     * Sets the master-detail link SoSalesReturnView between this object and <code>value</code>.
     */
    public void setSoSalesReturnView(Row value) {
        setAttributeInternal(SOSALESRETURNVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInItemsView.
     */
    public RowSet getAccInItemsView() {
        return (RowSet) getAttributeInternal(ACCINITEMSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncGetItemRateByLocDate.
     */
    public RowSet getAccVwFuncGetItemRateByLocDate() {
        return (RowSet) getAttributeInternal(ACCVWFUNCGETITEMRATEBYLOCDATE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncGetItemDiscountByLocationReturn.
     */
    public RowSet getAccVwFuncGetItemDiscountByLocationReturn() {
        return (RowSet) getAttributeInternal(ACCVWFUNCGETITEMDISCOUNTBYLOCATIONRETURN);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncGetItemAdditionalDiscount.
     */
    public RowSet getAccVwFuncGetItemAdditionalDiscount() {
        return (RowSet) getAttributeInternal(ACCVWFUNCGETITEMADDITIONALDISCOUNT);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getSoSalesReturnView().getAttribute("Posted").toString().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
    
}

