package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolscm.erpsolscmmodel.erpsolscmvo.common.SrimeiView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 30 16:40:11 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrimeiViewImpl extends ViewObjectImpl implements SrimeiView {
    /**
     * This is the default constructor (do not remove).
     */
    public SrimeiViewImpl() {
    }

    /**
     * Returns the variable value for P_ADF_SALESRETURNLINSEQ.
     * @return variable value for P_ADF_SALESRETURNLINSEQ
     */
    public Integer getP_ADF_SALESRETURNLINSEQ() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_SALESRETURNLINSEQ");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_SALESRETURNLINSEQ.
     * @param value value to bind as P_ADF_SALESRETURNLINSEQ
     */
    public void setP_ADF_SALESRETURNLINSEQ(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_SALESRETURNLINSEQ", value);
    }
    
    public void doERPSolRemoveSaleReturnBox() {
        try {
            //if selected box is null then exception will be handled
            String ERPSolBox = this.getCurrentRow().getAttribute("TempBoxNo").toString();
            this.setRangeSize(-1);

            for (int i = 0; i < this.getViewObject().getEstimatedRowCount(); i++) {
                try {//if row box no is null then system will move to next record in loop
                    if (getRowAtRangeIndex(i).getAttribute("TempBoxNo").toString().equals(ERPSolBox)) {
                        getRowAtRangeIndex(i).remove();
                        i--;
                    }
                } catch (Exception e) {
                    // TODO: Add catch code
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            // TODO: Add catch code
    //            e.printStackTrace();
        }

    }
}

