package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 01 11:15:35 PKT 2022
// ---------------------------------------------------------------------
public interface SoImeiMasterView extends ViewObject {
    void doSuperviseImeiEntry();
}

