package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 28 11:20:53 PKT 2021
// ---------------------------------------------------------------------
public interface SoRebateView extends ViewObject {
    void doSuperviseSalesRebate();
}

