package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 14 23:58:32 PKT 2021
// ---------------------------------------------------------------------
public interface SoSalesReturnView extends ViewObject {
    void doSuperviseSalesReturn();
}

