package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 18 09:35:20 PKT 2022
// ---------------------------------------------------------------------
public interface SoSalesReturnMemoView extends ViewObject {
    void doSuperviseSalesReturnMemo();
}

