package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 23 11:58:01 PKT 2021
// ---------------------------------------------------------------------
public interface SoSalesOrderView extends ViewObject {
    void doSuperviseSaleOrder();

    void doReadyForWarehouse();
}

