package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 03 00:03:49 PKT 2022
// ---------------------------------------------------------------------
public interface SoSalesOrderImeiView extends ViewObject {
    void doERPSolRemoveBox();
}

