package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 30 16:40:55 PKT 2022
// ---------------------------------------------------------------------
public interface SrimeiView extends ViewObject {
    void doERPSolRemoveSaleReturnBox();
}

