package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 13 10:03:31 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoProdDiscountImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Disclineno,
        Discountid,
        DiscountBasis,
        BaseValue,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        ValueBcurr,
        ValueOcurr,
        DiscountMode,
        ActValueBc,
        ActValueOc,
        Productid,
        Efrom,
        Eto,
        Locationid,
        SdPer,
        SdAmount,
        MaxDiscount,
        InItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DISCLINENO = AttributesEnum.Disclineno.index();
    public static final int DISCOUNTID = AttributesEnum.Discountid.index();
    public static final int DISCOUNTBASIS = AttributesEnum.DiscountBasis.index();
    public static final int BASEVALUE = AttributesEnum.BaseValue.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int VALUEBCURR = AttributesEnum.ValueBcurr.index();
    public static final int VALUEOCURR = AttributesEnum.ValueOcurr.index();
    public static final int DISCOUNTMODE = AttributesEnum.DiscountMode.index();
    public static final int ACTVALUEBC = AttributesEnum.ActValueBc.index();
    public static final int ACTVALUEOC = AttributesEnum.ActValueOc.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int EFROM = AttributesEnum.Efrom.index();
    public static final int ETO = AttributesEnum.Eto.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int SDPER = AttributesEnum.SdPer.index();
    public static final int SDAMOUNT = AttributesEnum.SdAmount.index();
    public static final int MAXDISCOUNT = AttributesEnum.MaxDiscount.index();
    public static final int INITEMS = AttributesEnum.InItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoProdDiscountImpl() {
    }

    /**
     * Gets the attribute value for Disclineno, using the alias name Disclineno.
     * @return the value of Disclineno
     */
    public Integer getDisclineno() {
        return (Integer) getAttributeInternal(DISCLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Disclineno.
     * @param value value to set the Disclineno
     */
    public void setDisclineno(Integer value) {
        setAttributeInternal(DISCLINENO, value);
    }

    /**
     * Gets the attribute value for Discountid, using the alias name Discountid.
     * @return the value of Discountid
     */
    public String getDiscountid() {
        return (String) getAttributeInternal(DISCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discountid.
     * @param value value to set the Discountid
     */
    public void setDiscountid(String value) {
        setAttributeInternal(DISCOUNTID, value);
    }

    /**
     * Gets the attribute value for DiscountBasis, using the alias name DiscountBasis.
     * @return the value of DiscountBasis
     */
    public String getDiscountBasis() {
        return (String) getAttributeInternal(DISCOUNTBASIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountBasis.
     * @param value value to set the DiscountBasis
     */
    public void setDiscountBasis(String value) {
        setAttributeInternal(DISCOUNTBASIS, value);
    }

    /**
     * Gets the attribute value for BaseValue, using the alias name BaseValue.
     * @return the value of BaseValue
     */
    public BigDecimal getBaseValue() {
        return (BigDecimal) getAttributeInternal(BASEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BaseValue.
     * @param value value to set the BaseValue
     */
    public void setBaseValue(BigDecimal value) {
        setAttributeInternal(BASEVALUE, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ValueBcurr, using the alias name ValueBcurr.
     * @return the value of ValueBcurr
     */
    public BigDecimal getValueBcurr() {
        return (BigDecimal) getAttributeInternal(VALUEBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueBcurr.
     * @param value value to set the ValueBcurr
     */
    public void setValueBcurr(BigDecimal value) {
        setAttributeInternal(VALUEBCURR, value);
    }

    /**
     * Gets the attribute value for ValueOcurr, using the alias name ValueOcurr.
     * @return the value of ValueOcurr
     */
    public BigDecimal getValueOcurr() {
        return (BigDecimal) getAttributeInternal(VALUEOCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueOcurr.
     * @param value value to set the ValueOcurr
     */
    public void setValueOcurr(BigDecimal value) {
        setAttributeInternal(VALUEOCURR, value);
    }

    /**
     * Gets the attribute value for DiscountMode, using the alias name DiscountMode.
     * @return the value of DiscountMode
     */
    public String getDiscountMode() {
        return (String) getAttributeInternal(DISCOUNTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountMode.
     * @param value value to set the DiscountMode
     */
    public void setDiscountMode(String value) {
        setAttributeInternal(DISCOUNTMODE, value);
    }

    /**
     * Gets the attribute value for ActValueBc, using the alias name ActValueBc.
     * @return the value of ActValueBc
     */
    public BigDecimal getActValueBc() {
        return (BigDecimal) getAttributeInternal(ACTVALUEBC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActValueBc.
     * @param value value to set the ActValueBc
     */
    public void setActValueBc(BigDecimal value) {
        setAttributeInternal(ACTVALUEBC, value);
    }

    /**
     * Gets the attribute value for ActValueOc, using the alias name ActValueOc.
     * @return the value of ActValueOc
     */
    public BigDecimal getActValueOc() {
        return (BigDecimal) getAttributeInternal(ACTVALUEOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActValueOc.
     * @param value value to set the ActValueOc
     */
    public void setActValueOc(BigDecimal value) {
        setAttributeInternal(ACTVALUEOC, value);
    }

    /**
     * Gets the attribute value for Productid, using the alias name Productid.
     * @return the value of Productid
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productid.
     * @param value value to set the Productid
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for Efrom, using the alias name Efrom.
     * @return the value of Efrom
     */
    public Date getEfrom() {
        return (Date) getAttributeInternal(EFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Efrom.
     * @param value value to set the Efrom
     */
    public void setEfrom(Date value) {
        setAttributeInternal(EFROM, value);
    }

    /**
     * Gets the attribute value for Eto, using the alias name Eto.
     * @return the value of Eto
     */
    public Date getEto() {
        return (Date) getAttributeInternal(ETO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Eto.
     * @param value value to set the Eto
     */
    public void setEto(Date value) {
        setAttributeInternal(ETO, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for SdPer, using the alias name SdPer.
     * @return the value of SdPer
     */
    public BigDecimal getSdPer() {
        return (BigDecimal) getAttributeInternal(SDPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SdPer.
     * @param value value to set the SdPer
     */
    public void setSdPer(BigDecimal value) {
        setAttributeInternal(SDPER, value);
    }

    /**
     * Gets the attribute value for SdAmount, using the alias name SdAmount.
     * @return the value of SdAmount
     */
    public BigDecimal getSdAmount() {
        return (BigDecimal) getAttributeInternal(SDAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SdAmount.
     * @param value value to set the SdAmount
     */
    public void setSdAmount(BigDecimal value) {
        setAttributeInternal(SDAMOUNT, value);
    }

    /**
     * Gets the attribute value for MaxDiscount, using the alias name MaxDiscount.
     * @return the value of MaxDiscount
     */
    public BigDecimal getMaxDiscount() {
        return (BigDecimal) getAttributeInternal(MAXDISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxDiscount.
     * @param value value to set the MaxDiscount
     */
    public void setMaxDiscount(BigDecimal value) {
        setAttributeInternal(MAXDISCOUNT, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInItems() {
        return (EntityImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInItems(EntityImpl value) {
        setAttributeInternal(INITEMS, value);
    }

    /**
     * @param disclineno key constituent
     * @param discountid key constituent
     * @param discountBasis key constituent
     * @param discountMode key constituent
     * @param productid key constituent
     * @param efrom key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer disclineno, String discountid, String discountBasis, String discountMode,
                                       String productid, Date efrom) {
        return new Key(new Object[] { disclineno, discountid, discountBasis, discountMode, productid, efrom });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.SoProdDiscount");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Disclineno");
        setERPSolPKSeqName("So_Prod_Discount_SEQ");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

