package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 28 11:05:34 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoRebateDetailImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RebateId,
        SalesQty,
        RebateQty,
        PreviousRate,
        CurrentRate,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        GenerateSo,
        Itemid,
        Productid,
        IsError,
        ErrorDesc,
        Discount,
        AddDiscount,
        FcurrPreviousRate,
        FcurrCurrentRate,
        GrouppId,
        SaleDate,
        Rebateseq,
        Rebatedetailseq,
        ManualRate,
        SoRebate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int REBATEID = AttributesEnum.RebateId.index();
    public static final int SALESQTY = AttributesEnum.SalesQty.index();
    public static final int REBATEQTY = AttributesEnum.RebateQty.index();
    public static final int PREVIOUSRATE = AttributesEnum.PreviousRate.index();
    public static final int CURRENTRATE = AttributesEnum.CurrentRate.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int GENERATESO = AttributesEnum.GenerateSo.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int ISERROR = AttributesEnum.IsError.index();
    public static final int ERRORDESC = AttributesEnum.ErrorDesc.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int ADDDISCOUNT = AttributesEnum.AddDiscount.index();
    public static final int FCURRPREVIOUSRATE = AttributesEnum.FcurrPreviousRate.index();
    public static final int FCURRCURRENTRATE = AttributesEnum.FcurrCurrentRate.index();
    public static final int GROUPPID = AttributesEnum.GrouppId.index();
    public static final int SALEDATE = AttributesEnum.SaleDate.index();
    public static final int REBATESEQ = AttributesEnum.Rebateseq.index();
    public static final int REBATEDETAILSEQ = AttributesEnum.Rebatedetailseq.index();
    public static final int MANUALRATE = AttributesEnum.ManualRate.index();
    public static final int SOREBATE = AttributesEnum.SoRebate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoRebateDetailImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.SoRebateDetail");
    }


    /**
     * Gets the attribute value for RebateId, using the alias name RebateId.
     * @return the value of RebateId
     */
    public String getRebateId() {
        return (String) getAttributeInternal(REBATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RebateId.
     * @param value value to set the RebateId
     */
    public void setRebateId(String value) {
        setAttributeInternal(REBATEID, value);
    }

    /**
     * Gets the attribute value for SalesQty, using the alias name SalesQty.
     * @return the value of SalesQty
     */
    public BigDecimal getSalesQty() {
        return (BigDecimal) getAttributeInternal(SALESQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesQty.
     * @param value value to set the SalesQty
     */
    public void setSalesQty(BigDecimal value) {
        setAttributeInternal(SALESQTY, value);
    }

    /**
     * Gets the attribute value for RebateQty, using the alias name RebateQty.
     * @return the value of RebateQty
     */
    public BigDecimal getRebateQty() {
        return (BigDecimal) getAttributeInternal(REBATEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RebateQty.
     * @param value value to set the RebateQty
     */
    public void setRebateQty(BigDecimal value) {
        setAttributeInternal(REBATEQTY, value);
    }

    /**
     * Gets the attribute value for PreviousRate, using the alias name PreviousRate.
     * @return the value of PreviousRate
     */
    public BigDecimal getPreviousRate() {
        return (BigDecimal) getAttributeInternal(PREVIOUSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousRate.
     * @param value value to set the PreviousRate
     */
    public void setPreviousRate(BigDecimal value) {
        setAttributeInternal(PREVIOUSRATE, value);
    }

    /**
     * Gets the attribute value for CurrentRate, using the alias name CurrentRate.
     * @return the value of CurrentRate
     */
    public BigDecimal getCurrentRate() {
        return (BigDecimal) getAttributeInternal(CURRENTRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentRate.
     * @param value value to set the CurrentRate
     */
    public void setCurrentRate(BigDecimal value) {
        setAttributeInternal(CURRENTRATE, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for GenerateSo, using the alias name GenerateSo.
     * @return the value of GenerateSo
     */
    public String getGenerateSo() {
        return (String) getAttributeInternal(GENERATESO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GenerateSo.
     * @param value value to set the GenerateSo
     */
    public void setGenerateSo(String value) {
        setAttributeInternal(GENERATESO, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for Productid, using the alias name Productid.
     * @return the value of Productid
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productid.
     * @param value value to set the Productid
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for IsError, using the alias name IsError.
     * @return the value of IsError
     */
    public String getIsError() {
        return (String) getAttributeInternal(ISERROR);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsError.
     * @param value value to set the IsError
     */
    public void setIsError(String value) {
        setAttributeInternal(ISERROR, value);
    }

    /**
     * Gets the attribute value for ErrorDesc, using the alias name ErrorDesc.
     * @return the value of ErrorDesc
     */
    public String getErrorDesc() {
        return (String) getAttributeInternal(ERRORDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorDesc.
     * @param value value to set the ErrorDesc
     */
    public void setErrorDesc(String value) {
        setAttributeInternal(ERRORDESC, value);
    }

    /**
     * Gets the attribute value for Discount, using the alias name Discount.
     * @return the value of Discount
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discount.
     * @param value value to set the Discount
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for AddDiscount, using the alias name AddDiscount.
     * @return the value of AddDiscount
     */
    public BigDecimal getAddDiscount() {
        return (BigDecimal) getAttributeInternal(ADDDISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddDiscount.
     * @param value value to set the AddDiscount
     */
    public void setAddDiscount(BigDecimal value) {
        setAttributeInternal(ADDDISCOUNT, value);
    }

    /**
     * Gets the attribute value for FcurrPreviousRate, using the alias name FcurrPreviousRate.
     * @return the value of FcurrPreviousRate
     */
    public BigDecimal getFcurrPreviousRate() {
        return (BigDecimal) getAttributeInternal(FCURRPREVIOUSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrPreviousRate.
     * @param value value to set the FcurrPreviousRate
     */
    public void setFcurrPreviousRate(BigDecimal value) {
        setAttributeInternal(FCURRPREVIOUSRATE, value);
    }

    /**
     * Gets the attribute value for FcurrCurrentRate, using the alias name FcurrCurrentRate.
     * @return the value of FcurrCurrentRate
     */
    public BigDecimal getFcurrCurrentRate() {
        return (BigDecimal) getAttributeInternal(FCURRCURRENTRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrCurrentRate.
     * @param value value to set the FcurrCurrentRate
     */
    public void setFcurrCurrentRate(BigDecimal value) {
        setAttributeInternal(FCURRCURRENTRATE, value);
    }

    /**
     * Gets the attribute value for GrouppId, using the alias name GrouppId.
     * @return the value of GrouppId
     */
    public Integer getGrouppId() {
        return (Integer) getAttributeInternal(GROUPPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrouppId.
     * @param value value to set the GrouppId
     */
    public void setGrouppId(Integer value) {
        setAttributeInternal(GROUPPID, value);
    }

    /**
     * Gets the attribute value for SaleDate, using the alias name SaleDate.
     * @return the value of SaleDate
     */
    public Date getSaleDate() {
        return (Date) getAttributeInternal(SALEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleDate.
     * @param value value to set the SaleDate
     */
    public void setSaleDate(Date value) {
        setAttributeInternal(SALEDATE, value);
    }

    /**
     * Gets the attribute value for Rebateseq, using the alias name Rebateseq.
     * @return the value of Rebateseq
     */
    public Integer getRebateseq() {
        return (Integer) getAttributeInternal(REBATESEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rebateseq.
     * @param value value to set the Rebateseq
     */
    public void setRebateseq(Integer value) {
        setAttributeInternal(REBATESEQ, value);
    }

    /**
     * Gets the attribute value for Rebatedetailseq, using the alias name Rebatedetailseq.
     * @return the value of Rebatedetailseq
     */
    public Integer getRebatedetailseq() {
        return (Integer) getAttributeInternal(REBATEDETAILSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rebatedetailseq.
     * @param value value to set the Rebatedetailseq
     */
    public void setRebatedetailseq(Integer value) {
        setAttributeInternal(REBATEDETAILSEQ, value);
    }

    /**
     * Gets the attribute value for ManualRate, using the alias name ManualRate.
     * @return the value of ManualRate
     */
    public BigDecimal getManualRate() {
        return (BigDecimal) getAttributeInternal(MANUALRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManualRate.
     * @param value value to set the ManualRate
     */
    public void setManualRate(BigDecimal value) {
        setAttributeInternal(MANUALRATE, value);
    }

    /**
     * @return the associated entity SoRebateImpl.
     */
    public SoRebateImpl getSoRebate() {
        return (SoRebateImpl) getAttributeInternal(SOREBATE);
    }

    /**
     * Sets <code>value</code> as the associated entity SoRebateImpl.
     */
    public void setSoRebate(SoRebateImpl value) {
        setAttributeInternal(SOREBATE, value);
    }


    /**
     * @param rebatedetailseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer rebatedetailseq) {
        return new Key(new Object[] { rebatedetailseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Rebatedetailseq");
        setERPSolPKSeqName("SO_REBATE_DETAIL_SEQ");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            populateAttributeAsChanged(REBATEID, getSoRebate().getAttribute("RebateId"));
       }
        super.doDML(operation, e);
    }
}

