package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.math.BigInteger;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 19 00:46:31 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoSalesOrderLinesImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Salesorderlineseq,
        Salesorderseq,
        Salesorderid,
        Lineno,
        Uomsid,
        Productid,
        ProductDescription,
        ModelNo,
        Quantity,
        MinSellingPrice,
        ActUnitPriceBcurr,
        ActUnitPriceOcurr,
        StdLineGrAmt,
        ActLineGrAmBcurr,
        ActLineGrAmtOcurr,
        LineOthChgBcurr,
        LineOthChgOcurr,
        LineNetAmtBcurr,
        LineNetAmtOcurr,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        StdUnitPriceBcurr,
        StdUnitPirceUs,
        TradeinDocid,
        StAmountBc,
        TradeinAmountBc,
        DiscountAmountBc,
        StAmountOc,
        TradeinAmountOc,
        DiscountAmountOc,
        Optional,
        Warranty,
        DeliveryDate,
        Deliverytermid,
        DelDays,
        ParentLineno,
        ReceiptDate,
        CoFlag,
        StaxExempt,
        ParentModel,
        CoExRate,
        UsSalePrice,
        QtyIssued,
        AvailQty,
        CurrQty,
        ProvAmount,
        SchemeId,
        SedAmountBc,
        SedAmountOc,
        SedExempt,
        ExtraTaxAmountBc,
        ExtraTaxAmountOc,
        ExtraTaxExempt,
        NetToNet,
        GiftQuantity,
        SoQuantity,
        DiscountUnit,
        DiscountPercent,
        TotSchemeSale,
        GiftDelivered,
        GiftRemaining,
        TotalGift,
        AddDiscountUnit,
        AddDiscountPercent,
        AddDiscountTotal,
        DefaultDiscAmount,
        AlreadyDelivered,
        FcurrAddDiscountTotal,
        PreviousGifts,
        LeaseIncomeAmtBcurr,
        LeaseIncomeAmtOcurr,
        ScAmount,
        GiftSchemeid,
        ExcludeSoQty,
        ExcludeGiftQty,
        EbsItemid,
        HiddenPercent,
        HiddenAmount,
        FlatPercent,
        FlatAmount,
        ConventionaPercent,
        ConventionalAmount,
        Scheme1Amount,
        Scheme2Amount,
        CostPrice,
        txtModelNo,
        txtGrossAmount,
        txtNetAmount,
        txtDiscountAmount,
        Itemid,
        txtPosted,
        txtAddDiscountTotal,
        txtDefaultDiscountAmount,
        SoSalesOrder,
        InItems,
        InItems1,
        SoDiscount,
        SoSalesOrderImei,
        AccVwFuncGetItemDiscountByLocDateInsert,
        FuncVwFuncGetCustomerCreditLimitStop;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESORDERLINESEQ = AttributesEnum.Salesorderlineseq.index();
    public static final int SALESORDERSEQ = AttributesEnum.Salesorderseq.index();
    public static final int SALESORDERID = AttributesEnum.Salesorderid.index();
    public static final int LINENO = AttributesEnum.Lineno.index();
    public static final int UOMSID = AttributesEnum.Uomsid.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int PRODUCTDESCRIPTION = AttributesEnum.ProductDescription.index();
    public static final int MODELNO = AttributesEnum.ModelNo.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int MINSELLINGPRICE = AttributesEnum.MinSellingPrice.index();
    public static final int ACTUNITPRICEBCURR = AttributesEnum.ActUnitPriceBcurr.index();
    public static final int ACTUNITPRICEOCURR = AttributesEnum.ActUnitPriceOcurr.index();
    public static final int STDLINEGRAMT = AttributesEnum.StdLineGrAmt.index();
    public static final int ACTLINEGRAMBCURR = AttributesEnum.ActLineGrAmBcurr.index();
    public static final int ACTLINEGRAMTOCURR = AttributesEnum.ActLineGrAmtOcurr.index();
    public static final int LINEOTHCHGBCURR = AttributesEnum.LineOthChgBcurr.index();
    public static final int LINEOTHCHGOCURR = AttributesEnum.LineOthChgOcurr.index();
    public static final int LINENETAMTBCURR = AttributesEnum.LineNetAmtBcurr.index();
    public static final int LINENETAMTOCURR = AttributesEnum.LineNetAmtOcurr.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STDUNITPRICEBCURR = AttributesEnum.StdUnitPriceBcurr.index();
    public static final int STDUNITPIRCEUS = AttributesEnum.StdUnitPirceUs.index();
    public static final int TRADEINDOCID = AttributesEnum.TradeinDocid.index();
    public static final int STAMOUNTBC = AttributesEnum.StAmountBc.index();
    public static final int TRADEINAMOUNTBC = AttributesEnum.TradeinAmountBc.index();
    public static final int DISCOUNTAMOUNTBC = AttributesEnum.DiscountAmountBc.index();
    public static final int STAMOUNTOC = AttributesEnum.StAmountOc.index();
    public static final int TRADEINAMOUNTOC = AttributesEnum.TradeinAmountOc.index();
    public static final int DISCOUNTAMOUNTOC = AttributesEnum.DiscountAmountOc.index();
    public static final int OPTIONAL = AttributesEnum.Optional.index();
    public static final int WARRANTY = AttributesEnum.Warranty.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int DELIVERYTERMID = AttributesEnum.Deliverytermid.index();
    public static final int DELDAYS = AttributesEnum.DelDays.index();
    public static final int PARENTLINENO = AttributesEnum.ParentLineno.index();
    public static final int RECEIPTDATE = AttributesEnum.ReceiptDate.index();
    public static final int COFLAG = AttributesEnum.CoFlag.index();
    public static final int STAXEXEMPT = AttributesEnum.StaxExempt.index();
    public static final int PARENTMODEL = AttributesEnum.ParentModel.index();
    public static final int COEXRATE = AttributesEnum.CoExRate.index();
    public static final int USSALEPRICE = AttributesEnum.UsSalePrice.index();
    public static final int QTYISSUED = AttributesEnum.QtyIssued.index();
    public static final int AVAILQTY = AttributesEnum.AvailQty.index();
    public static final int CURRQTY = AttributesEnum.CurrQty.index();
    public static final int PROVAMOUNT = AttributesEnum.ProvAmount.index();
    public static final int SCHEMEID = AttributesEnum.SchemeId.index();
    public static final int SEDAMOUNTBC = AttributesEnum.SedAmountBc.index();
    public static final int SEDAMOUNTOC = AttributesEnum.SedAmountOc.index();
    public static final int SEDEXEMPT = AttributesEnum.SedExempt.index();
    public static final int EXTRATAXAMOUNTBC = AttributesEnum.ExtraTaxAmountBc.index();
    public static final int EXTRATAXAMOUNTOC = AttributesEnum.ExtraTaxAmountOc.index();
    public static final int EXTRATAXEXEMPT = AttributesEnum.ExtraTaxExempt.index();
    public static final int NETTONET = AttributesEnum.NetToNet.index();
    public static final int GIFTQUANTITY = AttributesEnum.GiftQuantity.index();
    public static final int SOQUANTITY = AttributesEnum.SoQuantity.index();
    public static final int DISCOUNTUNIT = AttributesEnum.DiscountUnit.index();
    public static final int DISCOUNTPERCENT = AttributesEnum.DiscountPercent.index();
    public static final int TOTSCHEMESALE = AttributesEnum.TotSchemeSale.index();
    public static final int GIFTDELIVERED = AttributesEnum.GiftDelivered.index();
    public static final int GIFTREMAINING = AttributesEnum.GiftRemaining.index();
    public static final int TOTALGIFT = AttributesEnum.TotalGift.index();
    public static final int ADDDISCOUNTUNIT = AttributesEnum.AddDiscountUnit.index();
    public static final int ADDDISCOUNTPERCENT = AttributesEnum.AddDiscountPercent.index();
    public static final int ADDDISCOUNTTOTAL = AttributesEnum.AddDiscountTotal.index();
    public static final int DEFAULTDISCAMOUNT = AttributesEnum.DefaultDiscAmount.index();
    public static final int ALREADYDELIVERED = AttributesEnum.AlreadyDelivered.index();
    public static final int FCURRADDDISCOUNTTOTAL = AttributesEnum.FcurrAddDiscountTotal.index();
    public static final int PREVIOUSGIFTS = AttributesEnum.PreviousGifts.index();
    public static final int LEASEINCOMEAMTBCURR = AttributesEnum.LeaseIncomeAmtBcurr.index();
    public static final int LEASEINCOMEAMTOCURR = AttributesEnum.LeaseIncomeAmtOcurr.index();
    public static final int SCAMOUNT = AttributesEnum.ScAmount.index();
    public static final int GIFTSCHEMEID = AttributesEnum.GiftSchemeid.index();
    public static final int EXCLUDESOQTY = AttributesEnum.ExcludeSoQty.index();
    public static final int EXCLUDEGIFTQTY = AttributesEnum.ExcludeGiftQty.index();
    public static final int EBSITEMID = AttributesEnum.EbsItemid.index();
    public static final int HIDDENPERCENT = AttributesEnum.HiddenPercent.index();
    public static final int HIDDENAMOUNT = AttributesEnum.HiddenAmount.index();
    public static final int FLATPERCENT = AttributesEnum.FlatPercent.index();
    public static final int FLATAMOUNT = AttributesEnum.FlatAmount.index();
    public static final int CONVENTIONAPERCENT = AttributesEnum.ConventionaPercent.index();
    public static final int CONVENTIONALAMOUNT = AttributesEnum.ConventionalAmount.index();
    public static final int SCHEME1AMOUNT = AttributesEnum.Scheme1Amount.index();
    public static final int SCHEME2AMOUNT = AttributesEnum.Scheme2Amount.index();
    public static final int COSTPRICE = AttributesEnum.CostPrice.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int TXTGROSSAMOUNT = AttributesEnum.txtGrossAmount.index();
    public static final int TXTNETAMOUNT = AttributesEnum.txtNetAmount.index();
    public static final int TXTDISCOUNTAMOUNT = AttributesEnum.txtDiscountAmount.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int TXTPOSTED = AttributesEnum.txtPosted.index();
    public static final int TXTADDDISCOUNTTOTAL = AttributesEnum.txtAddDiscountTotal.index();
    public static final int TXTDEFAULTDISCOUNTAMOUNT = AttributesEnum.txtDefaultDiscountAmount.index();
    public static final int SOSALESORDER = AttributesEnum.SoSalesOrder.index();
    public static final int INITEMS = AttributesEnum.InItems.index();
    public static final int INITEMS1 = AttributesEnum.InItems1.index();
    public static final int SODISCOUNT = AttributesEnum.SoDiscount.index();
    public static final int SOSALESORDERIMEI = AttributesEnum.SoSalesOrderImei.index();
    public static final int ACCVWFUNCGETITEMDISCOUNTBYLOCDATEINSERT =
        AttributesEnum.AccVwFuncGetItemDiscountByLocDateInsert.index();
    public static final int FUNCVWFUNCGETCUSTOMERCREDITLIMITSTOP =
        AttributesEnum.FuncVwFuncGetCustomerCreditLimitStop.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoSalesOrderLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.SoSalesOrderLines");
    }


    /**
     * Gets the attribute value for Salesorderlineseq, using the alias name Salesorderlineseq.
     * @return the value of Salesorderlineseq
     */
    public Integer getSalesorderlineseq() {
        return (Integer) getAttributeInternal(SALESORDERLINESEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesorderlineseq.
     * @param value value to set the Salesorderlineseq
     */
    public void setSalesorderlineseq(Integer value) {
        setAttributeInternal(SALESORDERLINESEQ, value);
    }

    /**
     * Gets the attribute value for Salesorderseq, using the alias name Salesorderseq.
     * @return the value of Salesorderseq
     */
    public Integer getSalesorderseq() {
        return (Integer) getAttributeInternal(SALESORDERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesorderseq.
     * @param value value to set the Salesorderseq
     */
    public void setSalesorderseq(Integer value) {
        setAttributeInternal(SALESORDERSEQ, value);
    }

    /**
     * Gets the attribute value for Salesorderid, using the alias name Salesorderid.
     * @return the value of Salesorderid
     */
    public String getSalesorderid() {
        return (String) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesorderid.
     * @param value value to set the Salesorderid
     */
    public void setSalesorderid(String value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for Lineno, using the alias name Lineno.
     * @return the value of Lineno
     */
    public Integer getLineno() {
        return (Integer) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lineno.
     * @param value value to set the Lineno
     */
    public void setLineno(Integer value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for Uomsid, using the alias name Uomsid.
     * @return the value of Uomsid
     */
    public String getUomsid() {
        return (String) getAttributeInternal(UOMSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uomsid.
     * @param value value to set the Uomsid
     */
    public void setUomsid(String value) {
        setAttributeInternal(UOMSID, value);
    }

    /**
     * Gets the attribute value for Productid, using the alias name Productid.
     * @return the value of Productid
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productid.
     * @param value value to set the Productid
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for ProductDescription, using the alias name ProductDescription.
     * @return the value of ProductDescription
     */
    public String getProductDescription() {
        return (String) getAttributeInternal(PRODUCTDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductDescription.
     * @param value value to set the ProductDescription
     */
    public void setProductDescription(String value) {
        setAttributeInternal(PRODUCTDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ModelNo, using the alias name ModelNo.
     * @return the value of ModelNo
     */
    public String getModelNo() {
        return (String) getAttributeInternal(MODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModelNo.
     * @param value value to set the ModelNo
     */
    public void setModelNo(String value) {
        setAttributeInternal(MODELNO, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the value of Quantity
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for MinSellingPrice, using the alias name MinSellingPrice.
     * @return the value of MinSellingPrice
     */
    public BigDecimal getMinSellingPrice() {
        return (BigDecimal) getAttributeInternal(MINSELLINGPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinSellingPrice.
     * @param value value to set the MinSellingPrice
     */
    public void setMinSellingPrice(BigDecimal value) {
        setAttributeInternal(MINSELLINGPRICE, value);
    }

    /**
     * Gets the attribute value for ActUnitPriceBcurr, using the alias name ActUnitPriceBcurr.
     * @return the value of ActUnitPriceBcurr
     */
    public Integer getActUnitPriceBcurr() {
        return (Integer) getAttributeInternal(ACTUNITPRICEBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActUnitPriceBcurr.
     * @param value value to set the ActUnitPriceBcurr
     */
    public void setActUnitPriceBcurr(Integer value) {
        setAttributeInternal(ACTUNITPRICEBCURR, value);
    }

    /**
     * Gets the attribute value for ActUnitPriceOcurr, using the alias name ActUnitPriceOcurr.
     * @return the value of ActUnitPriceOcurr
     */
    public Integer getActUnitPriceOcurr() {
        return (Integer) getAttributeInternal(ACTUNITPRICEOCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActUnitPriceOcurr.
     * @param value value to set the ActUnitPriceOcurr
     */
    public void setActUnitPriceOcurr(Integer value) {
        setAttributeInternal(ACTUNITPRICEOCURR, value);
    }

    /**
     * Gets the attribute value for StdLineGrAmt, using the alias name StdLineGrAmt.
     * @return the value of StdLineGrAmt
     */
    public BigDecimal getStdLineGrAmt() {
        return (BigDecimal) getAttributeInternal(STDLINEGRAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for StdLineGrAmt.
     * @param value value to set the StdLineGrAmt
     */
    public void setStdLineGrAmt(BigDecimal value) {
        setAttributeInternal(STDLINEGRAMT, value);
    }

    /**
     * Gets the attribute value for ActLineGrAmBcurr, using the alias name ActLineGrAmBcurr.
     * @return the value of ActLineGrAmBcurr
     */
    public BigDecimal getActLineGrAmBcurr() {
        return (BigDecimal) getAttributeInternal(ACTLINEGRAMBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActLineGrAmBcurr.
     * @param value value to set the ActLineGrAmBcurr
     */
    public void setActLineGrAmBcurr(BigDecimal value) {
        setAttributeInternal(ACTLINEGRAMBCURR, value);
    }

    /**
     * Gets the attribute value for ActLineGrAmtOcurr, using the alias name ActLineGrAmtOcurr.
     * @return the value of ActLineGrAmtOcurr
     */
    public BigDecimal getActLineGrAmtOcurr() {
        return (BigDecimal) getAttributeInternal(ACTLINEGRAMTOCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActLineGrAmtOcurr.
     * @param value value to set the ActLineGrAmtOcurr
     */
    public void setActLineGrAmtOcurr(BigDecimal value) {
        setAttributeInternal(ACTLINEGRAMTOCURR, value);
    }

    /**
     * Gets the attribute value for LineOthChgBcurr, using the alias name LineOthChgBcurr.
     * @return the value of LineOthChgBcurr
     */
    public BigDecimal getLineOthChgBcurr() {
        return (BigDecimal) getAttributeInternal(LINEOTHCHGBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineOthChgBcurr.
     * @param value value to set the LineOthChgBcurr
     */
    public void setLineOthChgBcurr(BigDecimal value) {
        setAttributeInternal(LINEOTHCHGBCURR, value);
    }

    /**
     * Gets the attribute value for LineOthChgOcurr, using the alias name LineOthChgOcurr.
     * @return the value of LineOthChgOcurr
     */
    public BigDecimal getLineOthChgOcurr() {
        return (BigDecimal) getAttributeInternal(LINEOTHCHGOCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineOthChgOcurr.
     * @param value value to set the LineOthChgOcurr
     */
    public void setLineOthChgOcurr(BigDecimal value) {
        setAttributeInternal(LINEOTHCHGOCURR, value);
    }

    /**
     * Gets the attribute value for LineNetAmtBcurr, using the alias name LineNetAmtBcurr.
     * @return the value of LineNetAmtBcurr
     */
    public BigDecimal getLineNetAmtBcurr() {
        return (BigDecimal) getAttributeInternal(LINENETAMTBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNetAmtBcurr.
     * @param value value to set the LineNetAmtBcurr
     */
    public void setLineNetAmtBcurr(BigDecimal value) {
        setAttributeInternal(LINENETAMTBCURR, value);
    }

    /**
     * Gets the attribute value for LineNetAmtOcurr, using the alias name LineNetAmtOcurr.
     * @return the value of LineNetAmtOcurr
     */
    public BigDecimal getLineNetAmtOcurr() {
        return (BigDecimal) getAttributeInternal(LINENETAMTOCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNetAmtOcurr.
     * @param value value to set the LineNetAmtOcurr
     */
    public void setLineNetAmtOcurr(BigDecimal value) {
        setAttributeInternal(LINENETAMTOCURR, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for StdUnitPriceBcurr, using the alias name StdUnitPriceBcurr.
     * @return the value of StdUnitPriceBcurr
     */
    public BigDecimal getStdUnitPriceBcurr() {
        return (BigDecimal) getAttributeInternal(STDUNITPRICEBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for StdUnitPriceBcurr.
     * @param value value to set the StdUnitPriceBcurr
     */
    public void setStdUnitPriceBcurr(BigDecimal value) {
        setAttributeInternal(STDUNITPRICEBCURR, value);
    }

    /**
     * Gets the attribute value for StdUnitPirceUs, using the alias name StdUnitPirceUs.
     * @return the value of StdUnitPirceUs
     */
    public BigDecimal getStdUnitPirceUs() {
        return (BigDecimal) getAttributeInternal(STDUNITPIRCEUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for StdUnitPirceUs.
     * @param value value to set the StdUnitPirceUs
     */
    public void setStdUnitPirceUs(BigDecimal value) {
        setAttributeInternal(STDUNITPIRCEUS, value);
    }

    /**
     * Gets the attribute value for TradeinDocid, using the alias name TradeinDocid.
     * @return the value of TradeinDocid
     */
    public String getTradeinDocid() {
        return (String) getAttributeInternal(TRADEINDOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradeinDocid.
     * @param value value to set the TradeinDocid
     */
    public void setTradeinDocid(String value) {
        setAttributeInternal(TRADEINDOCID, value);
    }

    /**
     * Gets the attribute value for StAmountBc, using the alias name StAmountBc.
     * @return the value of StAmountBc
     */
    public BigDecimal getStAmountBc() {
        return (BigDecimal) getAttributeInternal(STAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StAmountBc.
     * @param value value to set the StAmountBc
     */
    public void setStAmountBc(BigDecimal value) {
        setAttributeInternal(STAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for TradeinAmountBc, using the alias name TradeinAmountBc.
     * @return the value of TradeinAmountBc
     */
    public BigDecimal getTradeinAmountBc() {
        return (BigDecimal) getAttributeInternal(TRADEINAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradeinAmountBc.
     * @param value value to set the TradeinAmountBc
     */
    public void setTradeinAmountBc(BigDecimal value) {
        setAttributeInternal(TRADEINAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for DiscountAmountBc, using the alias name DiscountAmountBc.
     * @return the value of DiscountAmountBc
     */
    public BigDecimal getDiscountAmountBc() {
        return (BigDecimal) getAttributeInternal(DISCOUNTAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountAmountBc.
     * @param value value to set the DiscountAmountBc
     */
    public void setDiscountAmountBc(BigDecimal value) {
        setAttributeInternal(DISCOUNTAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for StAmountOc, using the alias name StAmountOc.
     * @return the value of StAmountOc
     */
    public BigDecimal getStAmountOc() {
        return (BigDecimal) getAttributeInternal(STAMOUNTOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StAmountOc.
     * @param value value to set the StAmountOc
     */
    public void setStAmountOc(BigDecimal value) {
        setAttributeInternal(STAMOUNTOC, value);
    }

    /**
     * Gets the attribute value for TradeinAmountOc, using the alias name TradeinAmountOc.
     * @return the value of TradeinAmountOc
     */
    public BigDecimal getTradeinAmountOc() {
        return (BigDecimal) getAttributeInternal(TRADEINAMOUNTOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for TradeinAmountOc.
     * @param value value to set the TradeinAmountOc
     */
    public void setTradeinAmountOc(BigDecimal value) {
        setAttributeInternal(TRADEINAMOUNTOC, value);
    }

    /**
     * Gets the attribute value for DiscountAmountOc, using the alias name DiscountAmountOc.
     * @return the value of DiscountAmountOc
     */
    public BigDecimal getDiscountAmountOc() {
        return (BigDecimal) getAttributeInternal(DISCOUNTAMOUNTOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountAmountOc.
     * @param value value to set the DiscountAmountOc
     */
    public void setDiscountAmountOc(BigDecimal value) {
        setAttributeInternal(DISCOUNTAMOUNTOC, value);
    }

    /**
     * Gets the attribute value for Optional, using the alias name Optional.
     * @return the value of Optional
     */
    public String getOptional() {
        return (String) getAttributeInternal(OPTIONAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Optional.
     * @param value value to set the Optional
     */
    public void setOptional(String value) {
        setAttributeInternal(OPTIONAL, value);
    }

    /**
     * Gets the attribute value for Warranty, using the alias name Warranty.
     * @return the value of Warranty
     */
    public Integer getWarranty() {
        return (Integer) getAttributeInternal(WARRANTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Warranty.
     * @param value value to set the Warranty
     */
    public void setWarranty(Integer value) {
        setAttributeInternal(WARRANTY, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the value of DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for Deliverytermid, using the alias name Deliverytermid.
     * @return the value of Deliverytermid
     */
    public String getDeliverytermid() {
        return (String) getAttributeInternal(DELIVERYTERMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deliverytermid.
     * @param value value to set the Deliverytermid
     */
    public void setDeliverytermid(String value) {
        setAttributeInternal(DELIVERYTERMID, value);
    }

    /**
     * Gets the attribute value for DelDays, using the alias name DelDays.
     * @return the value of DelDays
     */
    public Integer getDelDays() {
        return (Integer) getAttributeInternal(DELDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DelDays.
     * @param value value to set the DelDays
     */
    public void setDelDays(Integer value) {
        setAttributeInternal(DELDAYS, value);
    }

    /**
     * Gets the attribute value for ParentLineno, using the alias name ParentLineno.
     * @return the value of ParentLineno
     */
    public Integer getParentLineno() {
        return (Integer) getAttributeInternal(PARENTLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentLineno.
     * @param value value to set the ParentLineno
     */
    public void setParentLineno(Integer value) {
        setAttributeInternal(PARENTLINENO, value);
    }

    /**
     * Gets the attribute value for ReceiptDate, using the alias name ReceiptDate.
     * @return the value of ReceiptDate
     */
    public Date getReceiptDate() {
        return (Date) getAttributeInternal(RECEIPTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceiptDate.
     * @param value value to set the ReceiptDate
     */
    public void setReceiptDate(Date value) {
        setAttributeInternal(RECEIPTDATE, value);
    }

    /**
     * Gets the attribute value for CoFlag, using the alias name CoFlag.
     * @return the value of CoFlag
     */
    public String getCoFlag() {
        return (String) getAttributeInternal(COFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoFlag.
     * @param value value to set the CoFlag
     */
    public void setCoFlag(String value) {
        setAttributeInternal(COFLAG, value);
    }

    /**
     * Gets the attribute value for StaxExempt, using the alias name StaxExempt.
     * @return the value of StaxExempt
     */
    public String getStaxExempt() {
        return (String) getAttributeInternal(STAXEXEMPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaxExempt.
     * @param value value to set the StaxExempt
     */
    public void setStaxExempt(String value) {
        setAttributeInternal(STAXEXEMPT, value);
    }

    /**
     * Gets the attribute value for ParentModel, using the alias name ParentModel.
     * @return the value of ParentModel
     */
    public String getParentModel() {
        return (String) getAttributeInternal(PARENTMODEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentModel.
     * @param value value to set the ParentModel
     */
    public void setParentModel(String value) {
        setAttributeInternal(PARENTMODEL, value);
    }

    /**
     * Gets the attribute value for CoExRate, using the alias name CoExRate.
     * @return the value of CoExRate
     */
    public BigDecimal getCoExRate() {
        return (BigDecimal) getAttributeInternal(COEXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoExRate.
     * @param value value to set the CoExRate
     */
    public void setCoExRate(BigDecimal value) {
        setAttributeInternal(COEXRATE, value);
    }

    /**
     * Gets the attribute value for UsSalePrice, using the alias name UsSalePrice.
     * @return the value of UsSalePrice
     */
    public BigDecimal getUsSalePrice() {
        return (BigDecimal) getAttributeInternal(USSALEPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsSalePrice.
     * @param value value to set the UsSalePrice
     */
    public void setUsSalePrice(BigDecimal value) {
        setAttributeInternal(USSALEPRICE, value);
    }

    /**
     * Gets the attribute value for QtyIssued, using the alias name QtyIssued.
     * @return the value of QtyIssued
     */
    public BigDecimal getQtyIssued() {
        return (BigDecimal) getAttributeInternal(QTYISSUED);
    }

    /**
     * Sets <code>value</code> as the attribute value for QtyIssued.
     * @param value value to set the QtyIssued
     */
    public void setQtyIssued(BigDecimal value) {
        setAttributeInternal(QTYISSUED, value);
    }

    /**
     * Gets the attribute value for AvailQty, using the alias name AvailQty.
     * @return the value of AvailQty
     */
    public Integer getAvailQty() {
        return (Integer) getAttributeInternal(AVAILQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AvailQty.
     * @param value value to set the AvailQty
     */
    public void setAvailQty(Integer value) {
        setAttributeInternal(AVAILQTY, value);
    }

    /**
     * Gets the attribute value for CurrQty, using the alias name CurrQty.
     * @return the value of CurrQty
     */
    public Integer getCurrQty() {
        return (Integer) getAttributeInternal(CURRQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrQty.
     * @param value value to set the CurrQty
     */
    public void setCurrQty(Integer value) {
        setAttributeInternal(CURRQTY, value);
    }

    /**
     * Gets the attribute value for ProvAmount, using the alias name ProvAmount.
     * @return the value of ProvAmount
     */
    public BigDecimal getProvAmount() {
        return (BigDecimal) getAttributeInternal(PROVAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProvAmount.
     * @param value value to set the ProvAmount
     */
    public void setProvAmount(BigDecimal value) {
        setAttributeInternal(PROVAMOUNT, value);
    }

    /**
     * Gets the attribute value for SchemeId, using the alias name SchemeId.
     * @return the value of SchemeId
     */
    public String getSchemeId() {
        return (String) getAttributeInternal(SCHEMEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SchemeId.
     * @param value value to set the SchemeId
     */
    public void setSchemeId(String value) {
        setAttributeInternal(SCHEMEID, value);
    }

    /**
     * Gets the attribute value for SedAmountBc, using the alias name SedAmountBc.
     * @return the value of SedAmountBc
     */
    public BigDecimal getSedAmountBc() {
        return (BigDecimal) getAttributeInternal(SEDAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SedAmountBc.
     * @param value value to set the SedAmountBc
     */
    public void setSedAmountBc(BigDecimal value) {
        setAttributeInternal(SEDAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for SedAmountOc, using the alias name SedAmountOc.
     * @return the value of SedAmountOc
     */
    public BigDecimal getSedAmountOc() {
        return (BigDecimal) getAttributeInternal(SEDAMOUNTOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SedAmountOc.
     * @param value value to set the SedAmountOc
     */
    public void setSedAmountOc(BigDecimal value) {
        setAttributeInternal(SEDAMOUNTOC, value);
    }

    /**
     * Gets the attribute value for SedExempt, using the alias name SedExempt.
     * @return the value of SedExempt
     */
    public String getSedExempt() {
        return (String) getAttributeInternal(SEDEXEMPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SedExempt.
     * @param value value to set the SedExempt
     */
    public void setSedExempt(String value) {
        setAttributeInternal(SEDEXEMPT, value);
    }

    /**
     * Gets the attribute value for ExtraTaxAmountBc, using the alias name ExtraTaxAmountBc.
     * @return the value of ExtraTaxAmountBc
     */
    public BigDecimal getExtraTaxAmountBc() {
        return (BigDecimal) getAttributeInternal(EXTRATAXAMOUNTBC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraTaxAmountBc.
     * @param value value to set the ExtraTaxAmountBc
     */
    public void setExtraTaxAmountBc(BigDecimal value) {
        setAttributeInternal(EXTRATAXAMOUNTBC, value);
    }

    /**
     * Gets the attribute value for ExtraTaxAmountOc, using the alias name ExtraTaxAmountOc.
     * @return the value of ExtraTaxAmountOc
     */
    public BigDecimal getExtraTaxAmountOc() {
        return (BigDecimal) getAttributeInternal(EXTRATAXAMOUNTOC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraTaxAmountOc.
     * @param value value to set the ExtraTaxAmountOc
     */
    public void setExtraTaxAmountOc(BigDecimal value) {
        setAttributeInternal(EXTRATAXAMOUNTOC, value);
    }

    /**
     * Gets the attribute value for ExtraTaxExempt, using the alias name ExtraTaxExempt.
     * @return the value of ExtraTaxExempt
     */
    public String getExtraTaxExempt() {
        return (String) getAttributeInternal(EXTRATAXEXEMPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraTaxExempt.
     * @param value value to set the ExtraTaxExempt
     */
    public void setExtraTaxExempt(String value) {
        setAttributeInternal(EXTRATAXEXEMPT, value);
    }

    /**
     * Gets the attribute value for NetToNet, using the alias name NetToNet.
     * @return the value of NetToNet
     */
    public String getNetToNet() {
        return (String) getAttributeInternal(NETTONET);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetToNet.
     * @param value value to set the NetToNet
     */
    public void setNetToNet(String value) {
        setAttributeInternal(NETTONET, value);
    }

    /**
     * Gets the attribute value for GiftQuantity, using the alias name GiftQuantity.
     * @return the value of GiftQuantity
     */
    public BigDecimal getGiftQuantity() {
        return (BigDecimal) getAttributeInternal(GIFTQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftQuantity.
     * @param value value to set the GiftQuantity
     */
    public void setGiftQuantity(BigDecimal value) {
        setAttributeInternal(GIFTQUANTITY, value);
    }

    /**
     * Gets the attribute value for SoQuantity, using the alias name SoQuantity.
     * @return the value of SoQuantity
     */
    public BigDecimal getSoQuantity() {
        return (BigDecimal) getAttributeInternal(SOQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoQuantity.
     * @param value value to set the SoQuantity
     */
    public void setSoQuantity(BigDecimal value) {
        setAttributeInternal(SOQUANTITY, value);
    }

    /**
     * Gets the attribute value for DiscountUnit, using the alias name DiscountUnit.
     * @return the value of DiscountUnit
     */
    public BigDecimal getDiscountUnit() {
        return (BigDecimal) getAttributeInternal(DISCOUNTUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountUnit.
     * @param value value to set the DiscountUnit
     */
    public void setDiscountUnit(BigDecimal value) {
        setAttributeInternal(DISCOUNTUNIT, value);
    }

    /**
     * Gets the attribute value for DiscountPercent, using the alias name DiscountPercent.
     * @return the value of DiscountPercent
     */
    public BigDecimal getDiscountPercent() {
        return (BigDecimal) getAttributeInternal(DISCOUNTPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiscountPercent.
     * @param value value to set the DiscountPercent
     */
    public void setDiscountPercent(BigDecimal value) {
        setAttributeInternal(DISCOUNTPERCENT, value);
    }

    /**
     * Gets the attribute value for TotSchemeSale, using the alias name TotSchemeSale.
     * @return the value of TotSchemeSale
     */
    public BigDecimal getTotSchemeSale() {
        return (BigDecimal) getAttributeInternal(TOTSCHEMESALE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotSchemeSale.
     * @param value value to set the TotSchemeSale
     */
    public void setTotSchemeSale(BigDecimal value) {
        setAttributeInternal(TOTSCHEMESALE, value);
    }

    /**
     * Gets the attribute value for GiftDelivered, using the alias name GiftDelivered.
     * @return the value of GiftDelivered
     */
    public BigDecimal getGiftDelivered() {
        return (BigDecimal) getAttributeInternal(GIFTDELIVERED);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftDelivered.
     * @param value value to set the GiftDelivered
     */
    public void setGiftDelivered(BigDecimal value) {
        setAttributeInternal(GIFTDELIVERED, value);
    }

    /**
     * Gets the attribute value for GiftRemaining, using the alias name GiftRemaining.
     * @return the value of GiftRemaining
     */
    public BigDecimal getGiftRemaining() {
        return (BigDecimal) getAttributeInternal(GIFTREMAINING);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftRemaining.
     * @param value value to set the GiftRemaining
     */
    public void setGiftRemaining(BigDecimal value) {
        setAttributeInternal(GIFTREMAINING, value);
    }

    /**
     * Gets the attribute value for TotalGift, using the alias name TotalGift.
     * @return the value of TotalGift
     */
    public BigDecimal getTotalGift() {
        return (BigDecimal) getAttributeInternal(TOTALGIFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalGift.
     * @param value value to set the TotalGift
     */
    public void setTotalGift(BigDecimal value) {
        setAttributeInternal(TOTALGIFT, value);
    }

    /**
     * Gets the attribute value for AddDiscountUnit, using the alias name AddDiscountUnit.
     * @return the value of AddDiscountUnit
     */
    public BigDecimal getAddDiscountUnit() {
        return (BigDecimal) getAttributeInternal(ADDDISCOUNTUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddDiscountUnit.
     * @param value value to set the AddDiscountUnit
     */
    public void setAddDiscountUnit(BigDecimal value) {
        setAttributeInternal(ADDDISCOUNTUNIT, value);
    }

    /**
     * Gets the attribute value for AddDiscountPercent, using the alias name AddDiscountPercent.
     * @return the value of AddDiscountPercent
     */
    public BigDecimal getAddDiscountPercent() {
        return (BigDecimal) getAttributeInternal(ADDDISCOUNTPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddDiscountPercent.
     * @param value value to set the AddDiscountPercent
     */
    public void setAddDiscountPercent(BigDecimal value) {
        setAttributeInternal(ADDDISCOUNTPERCENT, value);
    }

    /**
     * Gets the attribute value for AddDiscountTotal, using the alias name AddDiscountTotal.
     * @return the value of AddDiscountTotal
     */
    public BigDecimal getAddDiscountTotal() {
        return (BigDecimal) getAttributeInternal(ADDDISCOUNTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddDiscountTotal.
     * @param value value to set the AddDiscountTotal
     */
    public void setAddDiscountTotal(BigDecimal value) {
        setAttributeInternal(ADDDISCOUNTTOTAL, value);
    }

    /**
     * Gets the attribute value for DefaultDiscAmount, using the alias name DefaultDiscAmount.
     * @return the value of DefaultDiscAmount
     */
    public BigDecimal getDefaultDiscAmount() {
        return (BigDecimal) getAttributeInternal(DEFAULTDISCAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DefaultDiscAmount.
     * @param value value to set the DefaultDiscAmount
     */
    public void setDefaultDiscAmount(BigDecimal value) {
        setAttributeInternal(DEFAULTDISCAMOUNT, value);
    }

    /**
     * Gets the attribute value for AlreadyDelivered, using the alias name AlreadyDelivered.
     * @return the value of AlreadyDelivered
     */
    public BigDecimal getAlreadyDelivered() {
        return (BigDecimal) getAttributeInternal(ALREADYDELIVERED);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlreadyDelivered.
     * @param value value to set the AlreadyDelivered
     */
    public void setAlreadyDelivered(BigDecimal value) {
        setAttributeInternal(ALREADYDELIVERED, value);
    }

    /**
     * Gets the attribute value for FcurrAddDiscountTotal, using the alias name FcurrAddDiscountTotal.
     * @return the value of FcurrAddDiscountTotal
     */
    public BigDecimal getFcurrAddDiscountTotal() {
        return (BigDecimal) getAttributeInternal(FCURRADDDISCOUNTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for FcurrAddDiscountTotal.
     * @param value value to set the FcurrAddDiscountTotal
     */
    public void setFcurrAddDiscountTotal(BigDecimal value) {
        setAttributeInternal(FCURRADDDISCOUNTTOTAL, value);
    }

    /**
     * Gets the attribute value for PreviousGifts, using the alias name PreviousGifts.
     * @return the value of PreviousGifts
     */
    public Long getPreviousGifts() {
        return (Long) getAttributeInternal(PREVIOUSGIFTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousGifts.
     * @param value value to set the PreviousGifts
     */
    public void setPreviousGifts(Long value) {
        setAttributeInternal(PREVIOUSGIFTS, value);
    }

    /**
     * Gets the attribute value for LeaseIncomeAmtBcurr, using the alias name LeaseIncomeAmtBcurr.
     * @return the value of LeaseIncomeAmtBcurr
     */
    public BigDecimal getLeaseIncomeAmtBcurr() {
        return (BigDecimal) getAttributeInternal(LEASEINCOMEAMTBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseIncomeAmtBcurr.
     * @param value value to set the LeaseIncomeAmtBcurr
     */
    public void setLeaseIncomeAmtBcurr(BigDecimal value) {
        setAttributeInternal(LEASEINCOMEAMTBCURR, value);
    }

    /**
     * Gets the attribute value for LeaseIncomeAmtOcurr, using the alias name LeaseIncomeAmtOcurr.
     * @return the value of LeaseIncomeAmtOcurr
     */
    public BigDecimal getLeaseIncomeAmtOcurr() {
        return (BigDecimal) getAttributeInternal(LEASEINCOMEAMTOCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeaseIncomeAmtOcurr.
     * @param value value to set the LeaseIncomeAmtOcurr
     */
    public void setLeaseIncomeAmtOcurr(BigDecimal value) {
        setAttributeInternal(LEASEINCOMEAMTOCURR, value);
    }

    /**
     * Gets the attribute value for ScAmount, using the alias name ScAmount.
     * @return the value of ScAmount
     */
    public BigDecimal getScAmount() {
        return (BigDecimal) getAttributeInternal(SCAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScAmount.
     * @param value value to set the ScAmount
     */
    public void setScAmount(BigDecimal value) {
        setAttributeInternal(SCAMOUNT, value);
    }

    /**
     * Gets the attribute value for GiftSchemeid, using the alias name GiftSchemeid.
     * @return the value of GiftSchemeid
     */
    public String getGiftSchemeid() {
        return (String) getAttributeInternal(GIFTSCHEMEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftSchemeid.
     * @param value value to set the GiftSchemeid
     */
    public void setGiftSchemeid(String value) {
        setAttributeInternal(GIFTSCHEMEID, value);
    }

    /**
     * Gets the attribute value for ExcludeSoQty, using the alias name ExcludeSoQty.
     * @return the value of ExcludeSoQty
     */
    public BigDecimal getExcludeSoQty() {
        return (BigDecimal) getAttributeInternal(EXCLUDESOQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExcludeSoQty.
     * @param value value to set the ExcludeSoQty
     */
    public void setExcludeSoQty(BigDecimal value) {
        setAttributeInternal(EXCLUDESOQTY, value);
    }

    /**
     * Gets the attribute value for ExcludeGiftQty, using the alias name ExcludeGiftQty.
     * @return the value of ExcludeGiftQty
     */
    public BigDecimal getExcludeGiftQty() {
        return (BigDecimal) getAttributeInternal(EXCLUDEGIFTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExcludeGiftQty.
     * @param value value to set the ExcludeGiftQty
     */
    public void setExcludeGiftQty(BigDecimal value) {
        setAttributeInternal(EXCLUDEGIFTQTY, value);
    }

    /**
     * Gets the attribute value for EbsItemid, using the alias name EbsItemid.
     * @return the value of EbsItemid
     */
    public String getEbsItemid() {
        return (String) getAttributeInternal(EBSITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsItemid.
     * @param value value to set the EbsItemid
     */
    public void setEbsItemid(String value) {
        setAttributeInternal(EBSITEMID, value);
    }

    /**
     * Gets the attribute value for HiddenPercent, using the alias name HiddenPercent.
     * @return the value of HiddenPercent
     */
    public BigDecimal getHiddenPercent() {
        return (BigDecimal) getAttributeInternal(HIDDENPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for HiddenPercent.
     * @param value value to set the HiddenPercent
     */
    public void setHiddenPercent(BigDecimal value) {
        setAttributeInternal(HIDDENPERCENT, value);
    }

    /**
     * Gets the attribute value for HiddenAmount, using the alias name HiddenAmount.
     * @return the value of HiddenAmount
     */
    public BigDecimal getHiddenAmount() {
        return (BigDecimal) getAttributeInternal(HIDDENAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for HiddenAmount.
     * @param value value to set the HiddenAmount
     */
    public void setHiddenAmount(BigDecimal value) {
        setAttributeInternal(HIDDENAMOUNT, value);
    }

    /**
     * Gets the attribute value for FlatPercent, using the alias name FlatPercent.
     * @return the value of FlatPercent
     */
    public BigDecimal getFlatPercent() {
        return (BigDecimal) getAttributeInternal(FLATPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlatPercent.
     * @param value value to set the FlatPercent
     */
    public void setFlatPercent(BigDecimal value) {
        setAttributeInternal(FLATPERCENT, value);
    }

    /**
     * Gets the attribute value for FlatAmount, using the alias name FlatAmount.
     * @return the value of FlatAmount
     */
    public BigDecimal getFlatAmount() {
        return (BigDecimal) getAttributeInternal(FLATAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlatAmount.
     * @param value value to set the FlatAmount
     */
    public void setFlatAmount(BigDecimal value) {
        setAttributeInternal(FLATAMOUNT, value);
    }

    /**
     * Gets the attribute value for ConventionaPercent, using the alias name ConventionaPercent.
     * @return the value of ConventionaPercent
     */
    public BigDecimal getConventionaPercent() {
        return (BigDecimal) getAttributeInternal(CONVENTIONAPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConventionaPercent.
     * @param value value to set the ConventionaPercent
     */
    public void setConventionaPercent(BigDecimal value) {
        setAttributeInternal(CONVENTIONAPERCENT, value);
    }

    /**
     * Gets the attribute value for ConventionalAmount, using the alias name ConventionalAmount.
     * @return the value of ConventionalAmount
     */
    public BigDecimal getConventionalAmount() {
        return (BigDecimal) getAttributeInternal(CONVENTIONALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConventionalAmount.
     * @param value value to set the ConventionalAmount
     */
    public void setConventionalAmount(BigDecimal value) {
        setAttributeInternal(CONVENTIONALAMOUNT, value);
    }

    /**
     * Gets the attribute value for Scheme1Amount, using the alias name Scheme1Amount.
     * @return the value of Scheme1Amount
     */
    public BigDecimal getScheme1Amount() {
        return (BigDecimal) getAttributeInternal(SCHEME1AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Scheme1Amount.
     * @param value value to set the Scheme1Amount
     */
    public void setScheme1Amount(BigDecimal value) {
        setAttributeInternal(SCHEME1AMOUNT, value);
    }

    /**
     * Gets the attribute value for Scheme2Amount, using the alias name Scheme2Amount.
     * @return the value of Scheme2Amount
     */
    public BigDecimal getScheme2Amount() {
        return (BigDecimal) getAttributeInternal(SCHEME2AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Scheme2Amount.
     * @param value value to set the Scheme2Amount
     */
    public void setScheme2Amount(BigDecimal value) {
        setAttributeInternal(SCHEME2AMOUNT, value);
    }

    /**
     * Gets the attribute value for CostPrice, using the alias name CostPrice.
     * @return the value of CostPrice
     */
    public BigDecimal getCostPrice() {
        return (BigDecimal) getAttributeInternal(COSTPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostPrice.
     * @param value value to set the CostPrice
     */
    public void setCostPrice(BigDecimal value) {
        setAttributeInternal(COSTPRICE, value);
    }

    /**
     * Gets the attribute value for txtModelNo, using the alias name txtModelNo.
     * @return the value of txtModelNo
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtModelNo.
     * @param value value to set the txtModelNo
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * Gets the attribute value for txtGrossAmount, using the alias name txtGrossAmount.
     * @return the value of txtGrossAmount
     */
    public BigDecimal gettxtGrossAmount() {
        return (BigDecimal) getAttributeInternal(TXTGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtGrossAmount.
     * @param value value to set the txtGrossAmount
     */
    public void settxtGrossAmount(BigDecimal value) {
        setAttributeInternal(TXTGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for txtNetAmount, using the alias name txtNetAmount.
     * @return the value of txtNetAmount
     */
    public Integer gettxtNetAmount() {
        return (Integer) getAttributeInternal(TXTNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtNetAmount.
     * @param value value to set the txtNetAmount
     */
    public void settxtNetAmount(Integer value) {
        setAttributeInternal(TXTNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for txtDiscountAmount, using the alias name txtDiscountAmount.
     * @return the value of txtDiscountAmount
     */
    public BigDecimal gettxtDiscountAmount() {
        return (BigDecimal) getAttributeInternal(TXTDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtDiscountAmount.
     * @param value value to set the txtDiscountAmount
     */
    public void settxtDiscountAmount(BigDecimal value) {
        setAttributeInternal(TXTDISCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for txtPosted, using the alias name txtPosted.
     * @return the value of txtPosted
     */
    public String gettxtPosted() {
        return (String) getAttributeInternal(TXTPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPosted.
     * @param value value to set the txtPosted
     */
    public void settxtPosted(String value) {
        setAttributeInternal(TXTPOSTED, value);
    }

    /**
     * Gets the attribute value for txtAddDiscountTotal, using the alias name txtAddDiscountTotal.
     * @return the value of txtAddDiscountTotal
     */
    public BigDecimal gettxtAddDiscountTotal() {
        return (BigDecimal) getAttributeInternal(TXTADDDISCOUNTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtAddDiscountTotal.
     * @param value value to set the txtAddDiscountTotal
     */
    public void settxtAddDiscountTotal(BigDecimal value) {
        setAttributeInternal(TXTADDDISCOUNTTOTAL, value);
    }

    /**
     * Gets the attribute value for txtDefaultDiscountAmount, using the alias name txtDefaultDiscountAmount.
     * @return the value of txtDefaultDiscountAmount
     */
    public BigDecimal gettxtDefaultDiscountAmount() {
        return (BigDecimal) getAttributeInternal(TXTDEFAULTDISCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtDefaultDiscountAmount.
     * @param value value to set the txtDefaultDiscountAmount
     */
    public void settxtDefaultDiscountAmount(BigDecimal value) {
        setAttributeInternal(TXTDEFAULTDISCOUNTAMOUNT, value);
    }

    /**
     * @return the associated entity SoSalesOrderImpl.
     */
    public SoSalesOrderImpl getSoSalesOrder() {
        return (SoSalesOrderImpl) getAttributeInternal(SOSALESORDER);
    }

    /**
     * Sets <code>value</code> as the associated entity SoSalesOrderImpl.
     */
    public void setSoSalesOrder(SoSalesOrderImpl value) {
        setAttributeInternal(SOSALESORDER, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInItems() {
        return (EntityImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInItems(EntityImpl value) {
        setAttributeInternal(INITEMS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInItems1() {
        return (EntityImpl) getAttributeInternal(INITEMS1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInItems1(EntityImpl value) {
        setAttributeInternal(INITEMS1, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoDiscount() {
        return (RowIterator) getAttributeInternal(SODISCOUNT);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoSalesOrderImei() {
        return (RowIterator) getAttributeInternal(SOSALESORDERIMEI);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncGetItemDiscountByLocDateInsert.
     */
    public RowSet getAccVwFuncGetItemDiscountByLocDateInsert() {
        return (RowSet) getAttributeInternal(ACCVWFUNCGETITEMDISCOUNTBYLOCDATEINSERT);
    }


    /**
     * Gets the view accessor <code>RowSet</code> FuncVwFuncGetCustomerCreditLimitStop.
     */
    public RowSet getFuncVwFuncGetCustomerCreditLimitStop() {
        return (RowSet) getAttributeInternal(FUNCVWFUNCGETCUSTOMERCREDITLIMITSTOP);
    }


    /**
     * @param salesorderlineseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer salesorderlineseq) {
        return new Key(new Object[] { salesorderlineseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Salesorderlineseq");
        setERPSolPKSeqName("SO_SALES_ORDER_LINES_SEQ");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            System.out.println("this is a");
           populateAttributeAsChanged(SALESORDERID, getSoSalesOrder().getAttribute("Salesorderid").toString());
           String pkValue="FUNC_GET_MAX_ID('SO_SALES_ORDER_LINES WHERE SALESORDERID=''"+getSalesorderid()+"''','LINENO')";
           String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
           populateAttributeAsChanged(LINENO, Integer.parseInt(result));
        }
        if (operation!=DML_DELETE) {
           System.out.println("this is f");
            populateAttributeAsChanged(ACTLINEGRAMBCURR, (gettxtGrossAmount()==null?0:gettxtGrossAmount() ));
           System.out.println("this is g");
           populateAttributeAsChanged(ACTLINEGRAMTOCURR, (gettxtGrossAmount()==null?0:gettxtGrossAmount() ));
           System.out.println("this is h");
//           populateAttributeAsChanged(DISCOUNTAMOUNTOC, new BigDecimal(gettxtDiscountAmount()==null?0:gettxtDiscountAmount() ));
           populateAttributeAsChanged(DISCOUNTAMOUNTBC, getDiscountAmountOc());
           populateAttributeAsChanged(DEFAULTDISCAMOUNT, gettxtDefaultDiscountAmount());
           System.out.println("this is i");
           populateAttributeAsChanged(LINENETAMTBCURR, new BigDecimal(gettxtNetAmount()==null?0:gettxtNetAmount() ));
           System.out.println("this is j");
           populateAttributeAsChanged(LINENETAMTOCURR, gettxtNetAmount());
           System.out.println("this is k");
           populateAttributeAsChanged(ADDDISCOUNTTOTAL, gettxtAddDiscountTotal());
           
       }
        super.doDML(operation, e);
        if (operation!=DML_DELETE ) {
//FUNC_INSERT_DISCOUNT(P_USERID VARCHAR2,P_SALESORDERID VARCHAR2,P_CONFIRM_DATE DATE,P_TYPE VARCHAR2,P_CUSTOMERID VARCHAR2,P_PRODUCTID VARCHAR2,P_QUANTITY NUMBER,P_RATE NUMBER,P_EXCHANGE_RATE NUMBER,P_GIFT VARCHAR2,P_LINENO NUMBER) RETURN NUMBER IS
            String ERPPlsql="DECLARE L_RESULT NUMBER; begin L_RESULT:=PKG_SALE_ORDER.FUNC_INSERT_DISCOUNT(?,?,to_Date(?,'yyyy-mm-dd'),?,?,?,?,?,?,?,?); END;";
            CallableStatement cs = getDBTransaction().createCallableStatement(ERPPlsql, getDBTransaction().DEFAULT);
            try {
                cs.setString(1, ERPSolGlobClassModel.doGetUserCode());
                System.out.println("a");
                cs.setString(2,getSalesorderid());
                System.out.println("2");
                cs.setString(3, getSoSalesOrder().getAttribute("ConfirmDate").toString());
                System.out.println("3");
                cs.setString(4,"I");
                System.out.println("4");
                cs.setString(5,getSoSalesOrder().getAttribute("Customerid").toString());
                System.out.println("5");
                cs.setString(6,getProductid());
                System.out.println("6");
                cs.setString(7,getQuantity().toString());
                System.out.println("7");
                cs.setString(8,getActUnitPriceOcurr().toString());
                System.out.println("8");
                cs.setString(9,getSoSalesOrder().getAttribute("ExchangeRate").toString());
                System.out.println("9");
                cs.setString(10,getSoSalesOrder().getAttribute("Gift").toString());
                System.out.println("10");
                cs.setString(11,getLineno().toString());
                System.out.println("11");
                cs.executeUpdate();
                System.out.println(ERPPlsql);
            } catch (SQLException f) {
                f.printStackTrace();
            }
            finally{
                try {
                    cs.close();
                } catch (SQLException f) {
                }
            }

           
            
           
       }
        
//        if (operation==DML_DELETE) {
//            CallableStatement cs=null;
//            String ERPsolPLSQL="begin update item_imei_info set is_available='Y', customerid=null,sale_date=null ";
//            ERPsolPLSQL+=" where IMEI in(select soi.Imei_No from so_Sales_order_imei soi where soi.Salesorderlineseq="+getSalesorderlineseq()+"); end;";
//            System.out.println(ERPsolPLSQL);
//            cs=getDBTransaction().createCallableStatement(ERPsolPLSQL, getDBTransaction().DEFAULT);
//            try {
//                cs.executeUpdate();
//            } catch (SQLException f) {
//            }
//            finally{
//                try {
//                    cs.close();
//                } catch (SQLException f) {
//                }
//            }
//        }
    }
    
}

