package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 16 13:53:52 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoSalesOrderImpl extends ERPSolGlobalsEntityImpl {
    /**
     * Validation method for Customerid.
     */
    public boolean validateCustomerid(String customerid) {
        return true;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Salesorderseq,
        Salesorderid,
        Salesterritoryid,
        Sotypeid,
        Customerid,
        Statusid,
        Salespersonid,
        Locationid,
        Jobid,
        Basecurrid,
        Ordercurrid,
        ExchangeRate,
        CustomerDocRef,
        ContactName,
        CustomerDocDate,
        TransactionDate,
        DepositAmount,
        DepositAmountStatus,
        Flexfield1,
        IndentOrder,
        Flexfield2,
        Flexfield3,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        EarnestMoney,
        Posted,
        PostedBy,
        Paymenttermid,
        Tender,
        Validity,
        Companyid,
        Deptid,
        StPercent,
        OthDeposit,
        DueDate,
        ConfirmDate,
        HoBehalf,
        CustLocid,
        Pid,
        Remarks,
        Storeid,
        Custypeid,
        AssociateLocationid,
        GiftCustomerid,
        GiftSalesorderid,
        GiftSalespersonid,
        GiftPid,
        RefCustName,
        RefCustAdd,
        RefPhone,
        Scheme,
        SedPercent,
        ExtraTaxPercent,
        Divid,
        SoRefId,
        Gift,
        SoType,
        NetToNet,
        Supplierid,
        IsAuto,
        ReadyForIssue,
        RemainingCreditLimit,
        GiftWithoutScheme,
        IsMigrated,
        MigratedDate,
        RebateId,
        LpsdId,
        PosHeaderSno,
        LocCurrcode,
        InstallmentHeaderSno,
        SalesHeaderSno,
        Jobcardno,
        SubmitDate,
        ConsignmentNo,
        EbsCustomerId,
        EbsLocationId,
        EbsStoreId,
        EbsSalespersonId,
        Rnoteno,
        txtCustomerName,
        txtStoreName,
        txtSalesPersonName,
        txtSupplierName,
        txtErrorMessage,
        txtCurrentDate,
        txtScanType,
        txtLocationName,
        txtApplyCreditlimit,
        txtSalesTerritory,
        SoSalesOrderLines,
        AllCustomers,
        AllStores,
        SoSalesPersons,
        PuSuppliers,
        AllLocations,
        AccVwFuncCheckIsCustomerActive,
        AccVwFuncCheckSecurityCheque,
        AccVwFuncCheckCustomerCancelCheque,
        AccVwFuncCheckCustomerDBCQVO,
        AccVwFuncShowAgingAlert,
        AccVwFuncUserBackDateAllowed,
        AccVwFuncStopSaleLineOnAgingQVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESORDERSEQ = AttributesEnum.Salesorderseq.index();
    public static final int SALESORDERID = AttributesEnum.Salesorderid.index();
    public static final int SALESTERRITORYID = AttributesEnum.Salesterritoryid.index();
    public static final int SOTYPEID = AttributesEnum.Sotypeid.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int STATUSID = AttributesEnum.Statusid.index();
    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int JOBID = AttributesEnum.Jobid.index();
    public static final int BASECURRID = AttributesEnum.Basecurrid.index();
    public static final int ORDERCURRID = AttributesEnum.Ordercurrid.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int CUSTOMERDOCREF = AttributesEnum.CustomerDocRef.index();
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int CUSTOMERDOCDATE = AttributesEnum.CustomerDocDate.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int DEPOSITAMOUNT = AttributesEnum.DepositAmount.index();
    public static final int DEPOSITAMOUNTSTATUS = AttributesEnum.DepositAmountStatus.index();
    public static final int FLEXFIELD1 = AttributesEnum.Flexfield1.index();
    public static final int INDENTORDER = AttributesEnum.IndentOrder.index();
    public static final int FLEXFIELD2 = AttributesEnum.Flexfield2.index();
    public static final int FLEXFIELD3 = AttributesEnum.Flexfield3.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int EARNESTMONEY = AttributesEnum.EarnestMoney.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.PostedBy.index();
    public static final int PAYMENTTERMID = AttributesEnum.Paymenttermid.index();
    public static final int TENDER = AttributesEnum.Tender.index();
    public static final int VALIDITY = AttributesEnum.Validity.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int STPERCENT = AttributesEnum.StPercent.index();
    public static final int OTHDEPOSIT = AttributesEnum.OthDeposit.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int CONFIRMDATE = AttributesEnum.ConfirmDate.index();
    public static final int HOBEHALF = AttributesEnum.HoBehalf.index();
    public static final int CUSTLOCID = AttributesEnum.CustLocid.index();
    public static final int PID = AttributesEnum.Pid.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int CUSTYPEID = AttributesEnum.Custypeid.index();
    public static final int ASSOCIATELOCATIONID = AttributesEnum.AssociateLocationid.index();
    public static final int GIFTCUSTOMERID = AttributesEnum.GiftCustomerid.index();
    public static final int GIFTSALESORDERID = AttributesEnum.GiftSalesorderid.index();
    public static final int GIFTSALESPERSONID = AttributesEnum.GiftSalespersonid.index();
    public static final int GIFTPID = AttributesEnum.GiftPid.index();
    public static final int REFCUSTNAME = AttributesEnum.RefCustName.index();
    public static final int REFCUSTADD = AttributesEnum.RefCustAdd.index();
    public static final int REFPHONE = AttributesEnum.RefPhone.index();
    public static final int SCHEME = AttributesEnum.Scheme.index();
    public static final int SEDPERCENT = AttributesEnum.SedPercent.index();
    public static final int EXTRATAXPERCENT = AttributesEnum.ExtraTaxPercent.index();
    public static final int DIVID = AttributesEnum.Divid.index();
    public static final int SOREFID = AttributesEnum.SoRefId.index();
    public static final int GIFT = AttributesEnum.Gift.index();
    public static final int SOTYPE = AttributesEnum.SoType.index();
    public static final int NETTONET = AttributesEnum.NetToNet.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int ISAUTO = AttributesEnum.IsAuto.index();
    public static final int READYFORISSUE = AttributesEnum.ReadyForIssue.index();
    public static final int REMAININGCREDITLIMIT = AttributesEnum.RemainingCreditLimit.index();
    public static final int GIFTWITHOUTSCHEME = AttributesEnum.GiftWithoutScheme.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int REBATEID = AttributesEnum.RebateId.index();
    public static final int LPSDID = AttributesEnum.LpsdId.index();
    public static final int POSHEADERSNO = AttributesEnum.PosHeaderSno.index();
    public static final int LOCCURRCODE = AttributesEnum.LocCurrcode.index();
    public static final int INSTALLMENTHEADERSNO = AttributesEnum.InstallmentHeaderSno.index();
    public static final int SALESHEADERSNO = AttributesEnum.SalesHeaderSno.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int SUBMITDATE = AttributesEnum.SubmitDate.index();
    public static final int CONSIGNMENTNO = AttributesEnum.ConsignmentNo.index();
    public static final int EBSCUSTOMERID = AttributesEnum.EbsCustomerId.index();
    public static final int EBSLOCATIONID = AttributesEnum.EbsLocationId.index();
    public static final int EBSSTOREID = AttributesEnum.EbsStoreId.index();
    public static final int EBSSALESPERSONID = AttributesEnum.EbsSalespersonId.index();
    public static final int RNOTENO = AttributesEnum.Rnoteno.index();
    public static final int TXTCUSTOMERNAME = AttributesEnum.txtCustomerName.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int TXTSALESPERSONNAME = AttributesEnum.txtSalesPersonName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int TXTERRORMESSAGE = AttributesEnum.txtErrorMessage.index();
    public static final int TXTCURRENTDATE = AttributesEnum.txtCurrentDate.index();
    public static final int TXTSCANTYPE = AttributesEnum.txtScanType.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTAPPLYCREDITLIMIT = AttributesEnum.txtApplyCreditlimit.index();
    public static final int TXTSALESTERRITORY = AttributesEnum.txtSalesTerritory.index();
    public static final int SOSALESORDERLINES = AttributesEnum.SoSalesOrderLines.index();
    public static final int ALLCUSTOMERS = AttributesEnum.AllCustomers.index();
    public static final int ALLSTORES = AttributesEnum.AllStores.index();
    public static final int SOSALESPERSONS = AttributesEnum.SoSalesPersons.index();
    public static final int PUSUPPLIERS = AttributesEnum.PuSuppliers.index();
    public static final int ALLLOCATIONS = AttributesEnum.AllLocations.index();
    public static final int ACCVWFUNCCHECKISCUSTOMERACTIVE = AttributesEnum.AccVwFuncCheckIsCustomerActive.index();
    public static final int ACCVWFUNCCHECKSECURITYCHEQUE = AttributesEnum.AccVwFuncCheckSecurityCheque.index();
    public static final int ACCVWFUNCCHECKCUSTOMERCANCELCHEQUE =
        AttributesEnum.AccVwFuncCheckCustomerCancelCheque.index();
    public static final int ACCVWFUNCCHECKCUSTOMERDBCQVO = AttributesEnum.AccVwFuncCheckCustomerDBCQVO.index();
    public static final int ACCVWFUNCSHOWAGINGALERT = AttributesEnum.AccVwFuncShowAgingAlert.index();
    public static final int ACCVWFUNCUSERBACKDATEALLOWED = AttributesEnum.AccVwFuncUserBackDateAllowed.index();
    public static final int ACCVWFUNCSTOPSALELINEONAGINGQVO = AttributesEnum.AccVwFuncStopSaleLineOnAgingQVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoSalesOrderImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.SoSalesOrder");
    }


    /**
     * Gets the attribute value for Salesorderseq, using the alias name Salesorderseq.
     * @return the value of Salesorderseq
     */
    public Integer getSalesorderseq() {
        return (Integer) getAttributeInternal(SALESORDERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesorderseq.
     * @param value value to set the Salesorderseq
     */
    public void setSalesorderseq(Integer value) {
        setAttributeInternal(SALESORDERSEQ, value);
    }

    /**
     * Gets the attribute value for Salesorderid, using the alias name Salesorderid.
     * @return the value of Salesorderid
     */
    public String getSalesorderid() {
        return (String) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesorderid.
     * @param value value to set the Salesorderid
     */
    public void setSalesorderid(String value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for Salesterritoryid, using the alias name Salesterritoryid.
     * @return the value of Salesterritoryid
     */
    public String getSalesterritoryid() {
        return (String) getAttributeInternal(SALESTERRITORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesterritoryid.
     * @param value value to set the Salesterritoryid
     */
    public void setSalesterritoryid(String value) {
        setAttributeInternal(SALESTERRITORYID, value);
    }

    /**
     * Gets the attribute value for Sotypeid, using the alias name Sotypeid.
     * @return the value of Sotypeid
     */
    public String getSotypeid() {
        return (String) getAttributeInternal(SOTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sotypeid.
     * @param value value to set the Sotypeid
     */
    public void setSotypeid(String value) {
        setAttributeInternal(SOTYPEID, value);
    }

    /**
     * Gets the attribute value for Customerid, using the alias name Customerid.
     * @return the value of Customerid
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Customerid.
     * @param value value to set the Customerid
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for Statusid, using the alias name Statusid.
     * @return the value of Statusid
     */
    public String getStatusid() {
        return (String) getAttributeInternal(STATUSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Statusid.
     * @param value value to set the Statusid
     */
    public void setStatusid(String value) {
        setAttributeInternal(STATUSID, value);
    }

    /**
     * Gets the attribute value for Salespersonid, using the alias name Salespersonid.
     * @return the value of Salespersonid
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salespersonid.
     * @param value value to set the Salespersonid
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Jobid, using the alias name Jobid.
     * @return the value of Jobid
     */
    public String getJobid() {
        return (String) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobid.
     * @param value value to set the Jobid
     */
    public void setJobid(String value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for Basecurrid, using the alias name Basecurrid.
     * @return the value of Basecurrid
     */
    public String getBasecurrid() {
        return (String) getAttributeInternal(BASECURRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Basecurrid.
     * @param value value to set the Basecurrid
     */
    public void setBasecurrid(String value) {
        setAttributeInternal(BASECURRID, value);
    }

    /**
     * Gets the attribute value for Ordercurrid, using the alias name Ordercurrid.
     * @return the value of Ordercurrid
     */
    public String getOrdercurrid() {
        return (String) getAttributeInternal(ORDERCURRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ordercurrid.
     * @param value value to set the Ordercurrid
     */
    public void setOrdercurrid(String value) {
        setAttributeInternal(ORDERCURRID, value);
    }

    /**
     * Gets the attribute value for ExchangeRate, using the alias name ExchangeRate.
     * @return the value of ExchangeRate
     */
    public Double getExchangeRate() {
        return (Double) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExchangeRate.
     * @param value value to set the ExchangeRate
     */
    public void setExchangeRate(Double value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for CustomerDocRef, using the alias name CustomerDocRef.
     * @return the value of CustomerDocRef
     */
    public String getCustomerDocRef() {
        return (String) getAttributeInternal(CUSTOMERDOCREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerDocRef.
     * @param value value to set the CustomerDocRef
     */
    public void setCustomerDocRef(String value) {
        setAttributeInternal(CUSTOMERDOCREF, value);
    }

    /**
     * Gets the attribute value for ContactName, using the alias name ContactName.
     * @return the value of ContactName
     */
    public String getContactName() {
        return (String) getAttributeInternal(CONTACTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactName.
     * @param value value to set the ContactName
     */
    public void setContactName(String value) {
        setAttributeInternal(CONTACTNAME, value);
    }

    /**
     * Gets the attribute value for CustomerDocDate, using the alias name CustomerDocDate.
     * @return the value of CustomerDocDate
     */
    public Date getCustomerDocDate() {
        return (Date) getAttributeInternal(CUSTOMERDOCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerDocDate.
     * @param value value to set the CustomerDocDate
     */
    public void setCustomerDocDate(Date value) {
        setAttributeInternal(CUSTOMERDOCDATE, value);
    }

    /**
     * Gets the attribute value for TransactionDate, using the alias name TransactionDate.
     * @return the value of TransactionDate
     */
    public Date getTransactionDate() {
        return (Date) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionDate.
     * @param value value to set the TransactionDate
     */
    public void setTransactionDate(Date value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for DepositAmount, using the alias name DepositAmount.
     * @return the value of DepositAmount
     */
    public Integer getDepositAmount() {
        return (Integer) getAttributeInternal(DEPOSITAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepositAmount.
     * @param value value to set the DepositAmount
     */
    public void setDepositAmount(Integer value) {
        setAttributeInternal(DEPOSITAMOUNT, value);
    }

    /**
     * Gets the attribute value for DepositAmountStatus, using the alias name DepositAmountStatus.
     * @return the value of DepositAmountStatus
     */
    public String getDepositAmountStatus() {
        return (String) getAttributeInternal(DEPOSITAMOUNTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepositAmountStatus.
     * @param value value to set the DepositAmountStatus
     */
    public void setDepositAmountStatus(String value) {
        setAttributeInternal(DEPOSITAMOUNTSTATUS, value);
    }

    /**
     * Gets the attribute value for Flexfield1, using the alias name Flexfield1.
     * @return the value of Flexfield1
     */
    public String getFlexfield1() {
        return (String) getAttributeInternal(FLEXFIELD1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flexfield1.
     * @param value value to set the Flexfield1
     */
    public void setFlexfield1(String value) {
        setAttributeInternal(FLEXFIELD1, value);
    }

    /**
     * Gets the attribute value for IndentOrder, using the alias name IndentOrder.
     * @return the value of IndentOrder
     */
    public String getIndentOrder() {
        return (String) getAttributeInternal(INDENTORDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for IndentOrder.
     * @param value value to set the IndentOrder
     */
    public void setIndentOrder(String value) {
        setAttributeInternal(INDENTORDER, value);
    }

    /**
     * Gets the attribute value for Flexfield2, using the alias name Flexfield2.
     * @return the value of Flexfield2
     */
    public String getFlexfield2() {
        return (String) getAttributeInternal(FLEXFIELD2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flexfield2.
     * @param value value to set the Flexfield2
     */
    public void setFlexfield2(String value) {
        setAttributeInternal(FLEXFIELD2, value);
    }

    /**
     * Gets the attribute value for Flexfield3, using the alias name Flexfield3.
     * @return the value of Flexfield3
     */
    public String getFlexfield3() {
        return (String) getAttributeInternal(FLEXFIELD3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flexfield3.
     * @param value value to set the Flexfield3
     */
    public void setFlexfield3(String value) {
        setAttributeInternal(FLEXFIELD3, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for EarnestMoney, using the alias name EarnestMoney.
     * @return the value of EarnestMoney
     */
    public Double getEarnestMoney() {
        return (Double) getAttributeInternal(EARNESTMONEY);
    }

    /**
     * Sets <code>value</code> as the attribute value for EarnestMoney.
     * @param value value to set the EarnestMoney
     */
    public void setEarnestMoney(Double value) {
        setAttributeInternal(EARNESTMONEY, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for PostedBy, using the alias name PostedBy.
     * @return the value of PostedBy
     */
    public String getPostedBy() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedBy.
     * @param value value to set the PostedBy
     */
    public void setPostedBy(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for Paymenttermid, using the alias name Paymenttermid.
     * @return the value of Paymenttermid
     */
    public String getPaymenttermid() {
        return (String) getAttributeInternal(PAYMENTTERMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Paymenttermid.
     * @param value value to set the Paymenttermid
     */
    public void setPaymenttermid(String value) {
        setAttributeInternal(PAYMENTTERMID, value);
    }

    /**
     * Gets the attribute value for Tender, using the alias name Tender.
     * @return the value of Tender
     */
    public String getTender() {
        return (String) getAttributeInternal(TENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Tender.
     * @param value value to set the Tender
     */
    public void setTender(String value) {
        setAttributeInternal(TENDER, value);
    }

    /**
     * Gets the attribute value for Validity, using the alias name Validity.
     * @return the value of Validity
     */
    public Integer getValidity() {
        return (Integer) getAttributeInternal(VALIDITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Validity.
     * @param value value to set the Validity
     */
    public void setValidity(Integer value) {
        setAttributeInternal(VALIDITY, value);
    }

    /**
     * Gets the attribute value for Companyid, using the alias name Companyid.
     * @return the value of Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Companyid.
     * @param value value to set the Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for Deptid, using the alias name Deptid.
     * @return the value of Deptid
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deptid.
     * @param value value to set the Deptid
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for StPercent, using the alias name StPercent.
     * @return the value of StPercent
     */
    public Double getStPercent() {
        return (Double) getAttributeInternal(STPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for StPercent.
     * @param value value to set the StPercent
     */
    public void setStPercent(Double value) {
        setAttributeInternal(STPERCENT, value);
    }

    /**
     * Gets the attribute value for OthDeposit, using the alias name OthDeposit.
     * @return the value of OthDeposit
     */
    public Double getOthDeposit() {
        return (Double) getAttributeInternal(OTHDEPOSIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OthDeposit.
     * @param value value to set the OthDeposit
     */
    public void setOthDeposit(Double value) {
        setAttributeInternal(OTHDEPOSIT, value);
    }

    /**
     * Gets the attribute value for DueDate, using the alias name DueDate.
     * @return the value of DueDate
     */
    public Date getDueDate() {
        return (Date) getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DueDate.
     * @param value value to set the DueDate
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for ConfirmDate, using the alias name ConfirmDate.
     * @return the value of ConfirmDate
     */
    public Date getConfirmDate() {
        return (Date) getAttributeInternal(CONFIRMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConfirmDate.
     * @param value value to set the ConfirmDate
     */
    public void setConfirmDate(Date value) {
        setAttributeInternal(CONFIRMDATE, value);
    }

    /**
     * Gets the attribute value for HoBehalf, using the alias name HoBehalf.
     * @return the value of HoBehalf
     */
    public String getHoBehalf() {
        return (String) getAttributeInternal(HOBEHALF);
    }

    /**
     * Sets <code>value</code> as the attribute value for HoBehalf.
     * @param value value to set the HoBehalf
     */
    public void setHoBehalf(String value) {
        setAttributeInternal(HOBEHALF, value);
    }

    /**
     * Gets the attribute value for CustLocid, using the alias name CustLocid.
     * @return the value of CustLocid
     */
    public String getCustLocid() {
        return (String) getAttributeInternal(CUSTLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustLocid.
     * @param value value to set the CustLocid
     */
    public void setCustLocid(String value) {
        setAttributeInternal(CUSTLOCID, value);
    }

    /**
     * Gets the attribute value for Pid, using the alias name Pid.
     * @return the value of Pid
     */
    public Integer getPid() {
        return (Integer) getAttributeInternal(PID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pid.
     * @param value value to set the Pid
     */
    public void setPid(Integer value) {
        setAttributeInternal(PID, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Storeid, using the alias name Storeid.
     * @return the value of Storeid
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Storeid.
     * @param value value to set the Storeid
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for Custypeid, using the alias name Custypeid.
     * @return the value of Custypeid
     */
    public String getCustypeid() {
        return (String) getAttributeInternal(CUSTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Custypeid.
     * @param value value to set the Custypeid
     */
    public void setCustypeid(String value) {
        setAttributeInternal(CUSTYPEID, value);
    }

    /**
     * Gets the attribute value for AssociateLocationid, using the alias name AssociateLocationid.
     * @return the value of AssociateLocationid
     */
    public String getAssociateLocationid() {
        return (String) getAttributeInternal(ASSOCIATELOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssociateLocationid.
     * @param value value to set the AssociateLocationid
     */
    public void setAssociateLocationid(String value) {
        setAttributeInternal(ASSOCIATELOCATIONID, value);
    }

    /**
     * Gets the attribute value for GiftCustomerid, using the alias name GiftCustomerid.
     * @return the value of GiftCustomerid
     */
    public String getGiftCustomerid() {
        return (String) getAttributeInternal(GIFTCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftCustomerid.
     * @param value value to set the GiftCustomerid
     */
    public void setGiftCustomerid(String value) {
        setAttributeInternal(GIFTCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for GiftSalesorderid, using the alias name GiftSalesorderid.
     * @return the value of GiftSalesorderid
     */
    public String getGiftSalesorderid() {
        return (String) getAttributeInternal(GIFTSALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftSalesorderid.
     * @param value value to set the GiftSalesorderid
     */
    public void setGiftSalesorderid(String value) {
        setAttributeInternal(GIFTSALESORDERID, value);
    }

    /**
     * Gets the attribute value for GiftSalespersonid, using the alias name GiftSalespersonid.
     * @return the value of GiftSalespersonid
     */
    public String getGiftSalespersonid() {
        return (String) getAttributeInternal(GIFTSALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftSalespersonid.
     * @param value value to set the GiftSalespersonid
     */
    public void setGiftSalespersonid(String value) {
        setAttributeInternal(GIFTSALESPERSONID, value);
    }

    /**
     * Gets the attribute value for GiftPid, using the alias name GiftPid.
     * @return the value of GiftPid
     */
    public Integer getGiftPid() {
        return (Integer) getAttributeInternal(GIFTPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftPid.
     * @param value value to set the GiftPid
     */
    public void setGiftPid(Integer value) {
        setAttributeInternal(GIFTPID, value);
    }

    /**
     * Gets the attribute value for RefCustName, using the alias name RefCustName.
     * @return the value of RefCustName
     */
    public String getRefCustName() {
        return (String) getAttributeInternal(REFCUSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefCustName.
     * @param value value to set the RefCustName
     */
    public void setRefCustName(String value) {
        setAttributeInternal(REFCUSTNAME, value);
    }

    /**
     * Gets the attribute value for RefCustAdd, using the alias name RefCustAdd.
     * @return the value of RefCustAdd
     */
    public String getRefCustAdd() {
        return (String) getAttributeInternal(REFCUSTADD);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefCustAdd.
     * @param value value to set the RefCustAdd
     */
    public void setRefCustAdd(String value) {
        setAttributeInternal(REFCUSTADD, value);
    }

    /**
     * Gets the attribute value for RefPhone, using the alias name RefPhone.
     * @return the value of RefPhone
     */
    public String getRefPhone() {
        return (String) getAttributeInternal(REFPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefPhone.
     * @param value value to set the RefPhone
     */
    public void setRefPhone(String value) {
        setAttributeInternal(REFPHONE, value);
    }

    /**
     * Gets the attribute value for Scheme, using the alias name Scheme.
     * @return the value of Scheme
     */
    public String getScheme() {
        return (String) getAttributeInternal(SCHEME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Scheme.
     * @param value value to set the Scheme
     */
    public void setScheme(String value) {
        setAttributeInternal(SCHEME, value);
    }

    /**
     * Gets the attribute value for SedPercent, using the alias name SedPercent.
     * @return the value of SedPercent
     */
    public Double getSedPercent() {
        return (Double) getAttributeInternal(SEDPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SedPercent.
     * @param value value to set the SedPercent
     */
    public void setSedPercent(Double value) {
        setAttributeInternal(SEDPERCENT, value);
    }

    /**
     * Gets the attribute value for ExtraTaxPercent, using the alias name ExtraTaxPercent.
     * @return the value of ExtraTaxPercent
     */
    public Double getExtraTaxPercent() {
        return (Double) getAttributeInternal(EXTRATAXPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraTaxPercent.
     * @param value value to set the ExtraTaxPercent
     */
    public void setExtraTaxPercent(Double value) {
        setAttributeInternal(EXTRATAXPERCENT, value);
    }

    /**
     * Gets the attribute value for Divid, using the alias name Divid.
     * @return the value of Divid
     */
    public String getDivid() {
        return (String) getAttributeInternal(DIVID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Divid.
     * @param value value to set the Divid
     */
    public void setDivid(String value) {
        setAttributeInternal(DIVID, value);
    }

    /**
     * Gets the attribute value for SoRefId, using the alias name SoRefId.
     * @return the value of SoRefId
     */
    public String getSoRefId() {
        return (String) getAttributeInternal(SOREFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoRefId.
     * @param value value to set the SoRefId
     */
    public void setSoRefId(String value) {
        setAttributeInternal(SOREFID, value);
    }

    /**
     * Gets the attribute value for Gift, using the alias name Gift.
     * @return the value of Gift
     */
    public String getGift() {
        return (String) getAttributeInternal(GIFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gift.
     * @param value value to set the Gift
     */
    public void setGift(String value) {
        setAttributeInternal(GIFT, value);
    }

    /**
     * Gets the attribute value for SoType, using the alias name SoType.
     * @return the value of SoType
     */
    public String getSoType() {
        return (String) getAttributeInternal(SOTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoType.
     * @param value value to set the SoType
     */
    public void setSoType(String value) {
        setAttributeInternal(SOTYPE, value);
    }

    /**
     * Gets the attribute value for NetToNet, using the alias name NetToNet.
     * @return the value of NetToNet
     */
    public String getNetToNet() {
        return (String) getAttributeInternal(NETTONET);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetToNet.
     * @param value value to set the NetToNet
     */
    public void setNetToNet(String value) {
        setAttributeInternal(NETTONET, value);
    }

    /**
     * Gets the attribute value for Supplierid, using the alias name Supplierid.
     * @return the value of Supplierid
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supplierid.
     * @param value value to set the Supplierid
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for IsAuto, using the alias name IsAuto.
     * @return the value of IsAuto
     */
    public String getIsAuto() {
        return (String) getAttributeInternal(ISAUTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsAuto.
     * @param value value to set the IsAuto
     */
    public void setIsAuto(String value) {
        setAttributeInternal(ISAUTO, value);
    }

    /**
     * Gets the attribute value for ReadyForIssue, using the alias name ReadyForIssue.
     * @return the value of ReadyForIssue
     */
    public String getReadyForIssue() {
        return (String) getAttributeInternal(READYFORISSUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReadyForIssue.
     * @param value value to set the ReadyForIssue
     */
    public void setReadyForIssue(String value) {
        setAttributeInternal(READYFORISSUE, value);
    }

    /**
     * Gets the attribute value for RemainingCreditLimit, using the alias name RemainingCreditLimit.
     * @return the value of RemainingCreditLimit
     */
    public Integer getRemainingCreditLimit() {
        return (Integer) getAttributeInternal(REMAININGCREDITLIMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RemainingCreditLimit.
     * @param value value to set the RemainingCreditLimit
     */
    public void setRemainingCreditLimit(Integer value) {
        setAttributeInternal(REMAININGCREDITLIMIT, value);
    }

    /**
     * Gets the attribute value for GiftWithoutScheme, using the alias name GiftWithoutScheme.
     * @return the value of GiftWithoutScheme
     */
    public String getGiftWithoutScheme() {
        return (String) getAttributeInternal(GIFTWITHOUTSCHEME);
    }

    /**
     * Sets <code>value</code> as the attribute value for GiftWithoutScheme.
     * @param value value to set the GiftWithoutScheme
     */
    public void setGiftWithoutScheme(String value) {
        setAttributeInternal(GIFTWITHOUTSCHEME, value);
    }

    /**
     * Gets the attribute value for IsMigrated, using the alias name IsMigrated.
     * @return the value of IsMigrated
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsMigrated.
     * @param value value to set the IsMigrated
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MigratedDate, using the alias name MigratedDate.
     * @return the value of MigratedDate
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MigratedDate.
     * @param value value to set the MigratedDate
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for RebateId, using the alias name RebateId.
     * @return the value of RebateId
     */
    public String getRebateId() {
        return (String) getAttributeInternal(REBATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RebateId.
     * @param value value to set the RebateId
     */
    public void setRebateId(String value) {
        setAttributeInternal(REBATEID, value);
    }

    /**
     * Gets the attribute value for LpsdId, using the alias name LpsdId.
     * @return the value of LpsdId
     */
    public String getLpsdId() {
        return (String) getAttributeInternal(LPSDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LpsdId.
     * @param value value to set the LpsdId
     */
    public void setLpsdId(String value) {
        setAttributeInternal(LPSDID, value);
    }

    /**
     * Gets the attribute value for PosHeaderSno, using the alias name PosHeaderSno.
     * @return the value of PosHeaderSno
     */
    public Integer getPosHeaderSno() {
        return (Integer) getAttributeInternal(POSHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PosHeaderSno.
     * @param value value to set the PosHeaderSno
     */
    public void setPosHeaderSno(Integer value) {
        setAttributeInternal(POSHEADERSNO, value);
    }

    /**
     * Gets the attribute value for LocCurrcode, using the alias name LocCurrcode.
     * @return the value of LocCurrcode
     */
    public String getLocCurrcode() {
        return (String) getAttributeInternal(LOCCURRCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocCurrcode.
     * @param value value to set the LocCurrcode
     */
    public void setLocCurrcode(String value) {
        setAttributeInternal(LOCCURRCODE, value);
    }

    /**
     * Gets the attribute value for InstallmentHeaderSno, using the alias name InstallmentHeaderSno.
     * @return the value of InstallmentHeaderSno
     */
    public Integer getInstallmentHeaderSno() {
        return (Integer) getAttributeInternal(INSTALLMENTHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstallmentHeaderSno.
     * @param value value to set the InstallmentHeaderSno
     */
    public void setInstallmentHeaderSno(Integer value) {
        setAttributeInternal(INSTALLMENTHEADERSNO, value);
    }

    /**
     * Gets the attribute value for SalesHeaderSno, using the alias name SalesHeaderSno.
     * @return the value of SalesHeaderSno
     */
    public Integer getSalesHeaderSno() {
        return (Integer) getAttributeInternal(SALESHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesHeaderSno.
     * @param value value to set the SalesHeaderSno
     */
    public void setSalesHeaderSno(Integer value) {
        setAttributeInternal(SALESHEADERSNO, value);
    }

    /**
     * Gets the attribute value for Jobcardno, using the alias name Jobcardno.
     * @return the value of Jobcardno
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobcardno.
     * @param value value to set the Jobcardno
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
    }

    /**
     * Gets the attribute value for SubmitDate, using the alias name SubmitDate.
     * @return the value of SubmitDate
     */
    public Date getSubmitDate() {
        return (Date) getAttributeInternal(SUBMITDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitDate.
     * @param value value to set the SubmitDate
     */
    public void setSubmitDate(Date value) {
        setAttributeInternal(SUBMITDATE, value);
    }

    /**
     * Gets the attribute value for ConsignmentNo, using the alias name ConsignmentNo.
     * @return the value of ConsignmentNo
     */
    public String getConsignmentNo() {
        return (String) getAttributeInternal(CONSIGNMENTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConsignmentNo.
     * @param value value to set the ConsignmentNo
     */
    public void setConsignmentNo(String value) {
        setAttributeInternal(CONSIGNMENTNO, value);
    }

    /**
     * Gets the attribute value for EbsCustomerId, using the alias name EbsCustomerId.
     * @return the value of EbsCustomerId
     */
    public String getEbsCustomerId() {
        return (String) getAttributeInternal(EBSCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsCustomerId.
     * @param value value to set the EbsCustomerId
     */
    public void setEbsCustomerId(String value) {
        setAttributeInternal(EBSCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for EbsLocationId, using the alias name EbsLocationId.
     * @return the value of EbsLocationId
     */
    public String getEbsLocationId() {
        return (String) getAttributeInternal(EBSLOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsLocationId.
     * @param value value to set the EbsLocationId
     */
    public void setEbsLocationId(String value) {
        setAttributeInternal(EBSLOCATIONID, value);
    }

    /**
     * Gets the attribute value for EbsStoreId, using the alias name EbsStoreId.
     * @return the value of EbsStoreId
     */
    public String getEbsStoreId() {
        return (String) getAttributeInternal(EBSSTOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsStoreId.
     * @param value value to set the EbsStoreId
     */
    public void setEbsStoreId(String value) {
        setAttributeInternal(EBSSTOREID, value);
    }

    /**
     * Gets the attribute value for EbsSalespersonId, using the alias name EbsSalespersonId.
     * @return the value of EbsSalespersonId
     */
    public String getEbsSalespersonId() {
        return (String) getAttributeInternal(EBSSALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsSalespersonId.
     * @param value value to set the EbsSalespersonId
     */
    public void setEbsSalespersonId(String value) {
        setAttributeInternal(EBSSALESPERSONID, value);
    }

    /**
     * Gets the attribute value for Rnoteno, using the alias name Rnoteno.
     * @return the value of Rnoteno
     */
    public String getRnoteno() {
        return (String) getAttributeInternal(RNOTENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rnoteno.
     * @param value value to set the Rnoteno
     */
    public void setRnoteno(String value) {
        setAttributeInternal(RNOTENO, value);
    }

    /**
     * Gets the attribute value for txtCustomerName, using the alias name txtCustomerName.
     * @return the value of txtCustomerName
     */
    public String gettxtCustomerName() {
        return (String) getAttributeInternal(TXTCUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCustomerName.
     * @param value value to set the txtCustomerName
     */
    public void settxtCustomerName(String value) {
        setAttributeInternal(TXTCUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for txtStoreName, using the alias name txtStoreName.
     * @return the value of txtStoreName
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtStoreName.
     * @param value value to set the txtStoreName
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for txtSalesPersonName, using the alias name txtSalesPersonName.
     * @return the value of txtSalesPersonName
     */
    public String gettxtSalesPersonName() {
        return (String) getAttributeInternal(TXTSALESPERSONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSalesPersonName.
     * @param value value to set the txtSalesPersonName
     */
    public void settxtSalesPersonName(String value) {
        setAttributeInternal(TXTSALESPERSONNAME, value);
    }

    /**
     * Gets the attribute value for txtSupplierName, using the alias name txtSupplierName.
     * @return the value of txtSupplierName
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSupplierName.
     * @param value value to set the txtSupplierName
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for txtErrorMessage, using the alias name txtErrorMessage.
     * @return the value of txtErrorMessage
     */
    public String gettxtErrorMessage() {
        return (String) getAttributeInternal(TXTERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtErrorMessage.
     * @param value value to set the txtErrorMessage
     */
    public void settxtErrorMessage(String value) {
        setAttributeInternal(TXTERRORMESSAGE, value);
        
    }

    /**
     * Gets the attribute value for txtCurrentDate, using the alias name txtCurrentDate.
     * @return the value of txtCurrentDate
     */
    public Date gettxtCurrentDate() {
        return (Date) getAttributeInternal(TXTCURRENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCurrentDate.
     * @param value value to set the txtCurrentDate
     */
    public void settxtCurrentDate(Date value) {
        setAttributeInternal(TXTCURRENTDATE, value);
    }


    /**
     * Gets the attribute value for txtScanType, using the alias name txtScanType.
     * @return the value of txtScanType
     */
    public String gettxtScanType() {
        return (String) getAttributeInternal(TXTSCANTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtScanType.
     * @param value value to set the txtScanType
     */
    public void settxtScanType(String value) {
        setAttributeInternal(TXTSCANTYPE, value);
    }


    /**
     * Gets the attribute value for txtLocationName, using the alias name txtLocationName.
     * @return the value of txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtLocationName.
     * @param value value to set the txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for txtApplyCreditlimit, using the alias name txtApplyCreditlimit.
     * @return the value of txtApplyCreditlimit
     */
    public String gettxtApplyCreditlimit() {
        return (String) getAttributeInternal(TXTAPPLYCREDITLIMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtApplyCreditlimit.
     * @param value value to set the txtApplyCreditlimit
     */
    public void settxtApplyCreditlimit(String value) {
        setAttributeInternal(TXTAPPLYCREDITLIMIT, value);
    }

    /**
     * Gets the attribute value for txtSalesTerritory, using the alias name txtSalesTerritory.
     * @return the value of txtSalesTerritory
     */
    public String gettxtSalesTerritory() {
        return (String) getAttributeInternal(TXTSALESTERRITORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSalesTerritory.
     * @param value value to set the txtSalesTerritory
     */
    public void settxtSalesTerritory(String value) {
        setAttributeInternal(TXTSALESTERRITORY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoSalesOrderLines() {
        return (RowIterator) getAttributeInternal(SOSALESORDERLINES);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public AllCustomersImpl getAllCustomers() {
        return (AllCustomersImpl) getAttributeInternal(ALLCUSTOMERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllCustomers(AllCustomersImpl value) {
        setAttributeInternal(ALLCUSTOMERS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllStores() {
        return (EntityImpl) getAttributeInternal(ALLSTORES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllStores(EntityImpl value) {
        setAttributeInternal(ALLSTORES, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public SoSalesPersonsImpl getSoSalesPersons() {
        return (SoSalesPersonsImpl) getAttributeInternal(SOSALESPERSONS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSoSalesPersons(SoSalesPersonsImpl value) {
        setAttributeInternal(SOSALESPERSONS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getPuSuppliers() {
        return (EntityImpl) getAttributeInternal(PUSUPPLIERS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setPuSuppliers(EntityImpl value) {
        setAttributeInternal(PUSUPPLIERS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllLocations() {
        return (EntityImpl) getAttributeInternal(ALLLOCATIONS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllLocations(EntityImpl value) {
        setAttributeInternal(ALLLOCATIONS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncCheckIsCustomerActive.
     */
    public RowSet getAccVwFuncCheckIsCustomerActive() {
        return (RowSet) getAttributeInternal(ACCVWFUNCCHECKISCUSTOMERACTIVE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncCheckSecurityCheque.
     */
    public RowSet getAccVwFuncCheckSecurityCheque() {
        return (RowSet) getAttributeInternal(ACCVWFUNCCHECKSECURITYCHEQUE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncCheckCustomerCancelCheque.
     */
    public RowSet getAccVwFuncCheckCustomerCancelCheque() {
        return (RowSet) getAttributeInternal(ACCVWFUNCCHECKCUSTOMERCANCELCHEQUE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncCheckCustomerDBCQVO.
     */
    public RowSet getAccVwFuncCheckCustomerDBCQVO() {
        return (RowSet) getAttributeInternal(ACCVWFUNCCHECKCUSTOMERDBCQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncShowAgingAlert.
     */
    public RowSet getAccVwFuncShowAgingAlert() {
        return (RowSet) getAttributeInternal(ACCVWFUNCSHOWAGINGALERT);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncUserBackDateAllowed.
     */
    public RowSet getAccVwFuncUserBackDateAllowed() {
        return (RowSet) getAttributeInternal(ACCVWFUNCUSERBACKDATEALLOWED);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccVwFuncStopSaleLineOnAgingQVO.
     */
    public RowSet getAccVwFuncStopSaleLineOnAgingQVO() {
        return (RowSet) getAttributeInternal(ACCVWFUNCSTOPSALELINEONAGINGQVO);
    }

    /**
     * @param salesorderseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer salesorderseq) {
        return new Key(new Object[] { salesorderseq });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        if (operation==DML_INSERT) {
            String pkValue=" SALESORDER_ID('"+ERPSolGlobClassModel.doGetUserCompanyCode()+"','"+ERPSolGlobClassModel.doGetUserLocationCode()+"','"+getStoreid()+"',TO_DATE('"+getConfirmDate()+"','YYYY-MM-DD'))";
            System.out.println(pkValue + "pk value");
            String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
            populateAttributeAsChanged(SALESORDERID, result);
            populateAttributeAsChanged(SALESTERRITORYID, gettxtSalesTerritory());
        }
        else if (operation==DML_UPDATE) {
           populateAttributeAsChanged(SALESTERRITORYID, gettxtSalesTerritory());
            if (getPosted().equals("Y")) {
                populateAttributeAsChanged(POSTEDBY, ERPSolGlobClassModel.doGetUserCode());
               
           }
       }
        super.doDML(operation, e);
    }
    @Override
    protected void create(AttributeList attributeList) {
        // TODO Implement this method
        setERPSolPKColumnName("Salesorderseq");
        setERPSolPKSeqName("SO_SALES_ORDER_SEQ");
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
        setStoreid(ERPSolGlobClassModel.doGetUserStoreCode());
        setCompanyid(ERPSolGlobClassModel.doGetUserCompanyCode());
//        setERPISGenertePK("NO");    
//        SequenceImpl seq = new SequenceImpl("SO_SALES_ORDER_SEQ", getDBTransaction());
//        setSalesorderseq(seq.getSequenceNumber());
        super.create(attributeList);
    }
}

