package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 12 13:31:10 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoSalesPersonsImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Salespersonid,
        Salesterritoryid,
        Empid,
        Name,
        CommissionAllowed,
        IncentiveAllowed,
        RepMgr,
        Locationid,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        ChqReturn,
        EbsSalespersonId,
        Salespersonseq,
        SoSalesOrder,
        AllCustomerSalesperson,
        SoSalesReturn,
        SoRebate,
        SoSalesReturnMemo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESPERSONID = AttributesEnum.Salespersonid.index();
    public static final int SALESTERRITORYID = AttributesEnum.Salesterritoryid.index();
    public static final int EMPID = AttributesEnum.Empid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int COMMISSIONALLOWED = AttributesEnum.CommissionAllowed.index();
    public static final int INCENTIVEALLOWED = AttributesEnum.IncentiveAllowed.index();
    public static final int REPMGR = AttributesEnum.RepMgr.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int CHQRETURN = AttributesEnum.ChqReturn.index();
    public static final int EBSSALESPERSONID = AttributesEnum.EbsSalespersonId.index();
    public static final int SALESPERSONSEQ = AttributesEnum.Salespersonseq.index();
    public static final int SOSALESORDER = AttributesEnum.SoSalesOrder.index();
    public static final int ALLCUSTOMERSALESPERSON = AttributesEnum.AllCustomerSalesperson.index();
    public static final int SOSALESRETURN = AttributesEnum.SoSalesReturn.index();
    public static final int SOREBATE = AttributesEnum.SoRebate.index();
    public static final int SOSALESRETURNMEMO = AttributesEnum.SoSalesReturnMemo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SoSalesPersonsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.SoSalesPersons");
    }


    /**
     * Gets the attribute value for Salespersonid, using the alias name Salespersonid.
     * @return the value of Salespersonid
     */
    public String getSalespersonid() {
        return (String) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salespersonid.
     * @param value value to set the Salespersonid
     */
    public void setSalespersonid(String value) {
        setAttributeInternal(SALESPERSONID, value);
    }

    /**
     * Gets the attribute value for Salesterritoryid, using the alias name Salesterritoryid.
     * @return the value of Salesterritoryid
     */
    public String getSalesterritoryid() {
        return (String) getAttributeInternal(SALESTERRITORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesterritoryid.
     * @param value value to set the Salesterritoryid
     */
    public void setSalesterritoryid(String value) {
        setAttributeInternal(SALESTERRITORYID, value);
    }

    /**
     * Gets the attribute value for Empid, using the alias name Empid.
     * @return the value of Empid
     */
    public String getEmpid() {
        return (String) getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Empid.
     * @param value value to set the Empid
     */
    public void setEmpid(String value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for CommissionAllowed, using the alias name CommissionAllowed.
     * @return the value of CommissionAllowed
     */
    public String getCommissionAllowed() {
        return (String) getAttributeInternal(COMMISSIONALLOWED);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommissionAllowed.
     * @param value value to set the CommissionAllowed
     */
    public void setCommissionAllowed(String value) {
        setAttributeInternal(COMMISSIONALLOWED, value);
    }

    /**
     * Gets the attribute value for IncentiveAllowed, using the alias name IncentiveAllowed.
     * @return the value of IncentiveAllowed
     */
    public String getIncentiveAllowed() {
        return (String) getAttributeInternal(INCENTIVEALLOWED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncentiveAllowed.
     * @param value value to set the IncentiveAllowed
     */
    public void setIncentiveAllowed(String value) {
        setAttributeInternal(INCENTIVEALLOWED, value);
    }

    /**
     * Gets the attribute value for RepMgr, using the alias name RepMgr.
     * @return the value of RepMgr
     */
    public String getRepMgr() {
        return (String) getAttributeInternal(REPMGR);
    }

    /**
     * Sets <code>value</code> as the attribute value for RepMgr.
     * @param value value to set the RepMgr
     */
    public void setRepMgr(String value) {
        setAttributeInternal(REPMGR, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ChqReturn, using the alias name ChqReturn.
     * @return the value of ChqReturn
     */
    public String getChqReturn() {
        return (String) getAttributeInternal(CHQRETURN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChqReturn.
     * @param value value to set the ChqReturn
     */
    public void setChqReturn(String value) {
        setAttributeInternal(CHQRETURN, value);
    }

    /**
     * Gets the attribute value for EbsSalespersonId, using the alias name EbsSalespersonId.
     * @return the value of EbsSalespersonId
     */
    public String getEbsSalespersonId() {
        return (String) getAttributeInternal(EBSSALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsSalespersonId.
     * @param value value to set the EbsSalespersonId
     */
    public void setEbsSalespersonId(String value) {
        setAttributeInternal(EBSSALESPERSONID, value);
    }

    /**
     * Gets the attribute value for Salespersonseq, using the alias name Salespersonseq.
     * @return the value of Salespersonseq
     */
    public Integer getSalespersonseq() {
        return (Integer) getAttributeInternal(SALESPERSONSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salespersonseq.
     * @param value value to set the Salespersonseq
     */
    public void setSalespersonseq(Integer value) {
        setAttributeInternal(SALESPERSONSEQ, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoSalesOrder() {
        return (RowIterator) getAttributeInternal(SOSALESORDER);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAllCustomerSalesperson() {
        return (RowIterator) getAttributeInternal(ALLCUSTOMERSALESPERSON);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoSalesReturn() {
        return (RowIterator) getAttributeInternal(SOSALESRETURN);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoRebate() {
        return (RowIterator) getAttributeInternal(SOREBATE);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoSalesReturnMemo() {
        return (RowIterator) getAttributeInternal(SOSALESRETURNMEMO);
    }


    /**
     * @param salespersonid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String salespersonid) {
        return new Key(new Object[] { salespersonid });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Salespersonseq");
        setERPSolPKSeqName("SO_SALES_PERSONS_SEQ");
        
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

